### ISSUE TITLE
Add Test Containers

### ISSUE THREAD

**Issue by omarlarus** [neo4j-contrib/neo4j-streams#11]
Integration tests using Docker like ETL

**Comment by jexp** [comment]
@albertodelazzari did you check how well testcontainers work on Travis CI ?
Otherwise I can als see how to add it to TeamCity.

**Comment by albertodelazzari** [comment]
> @albertodelazzari did you check how well testcontainers work on Travis CI ?
> Otherwise I can als see how to add it to TeamCity.

No, but I can if you want. What we need is at least Docker v1.10 and maybe do some config stuff on `.travis.yml`
