### ISSUE TITLE
Multiple Node Topic Patterns Don't Work

### ISSUE THREAD

**Issue by DevanshModi** [neo4j-contrib/neo4j-streams#110]
## Expected Behavior (Mandatory)
Messages should go to the right topic based on the patterns defined in the neo4j.conf file

## Actual Behavior (Mandatory)
Messages, irrespective of the topic patterns, are going to all the topics.

## How to Reproduce the Problem
My current pattern config for nodes looks like this:
streams.procedures.enabled=true                                                                                                                                                           `streams.source.topic.nodes.neo4j-product=Product{name1, name2}                                                                                                                        streams.source.topic.nodes.neo4j-color=Color{*}                                                                                                                               streams.source.topic.nodes.neo4j-idnum=IDNUM{*}`

Now when I change a node, Product for instance, a message is sent to all the three topics above. It should be going to only the neo4j-product topic. What am I doing wrong, or is this a bug?

--
Currently used versions

### Versions

  - OS:
  - Neo4j: 3.4.6
  - Neo4j-Streams: latest JAR

**Comment by conker84** [comment]
Hi @DevanshModi can you try with this jar?
Thanks a lot for your feedback!
[neo4j-streams-3.4.0.jar.zip](https://github.com/neo4j-contrib/neo4j-streams/files/2732152/neo4j-streams-3.4.0.jar.zip)
