### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by conker84** [neo4j-contrib/neo4j-streams#123]
1. Connectors MUST NOT throw RuntimeException unless it encounters a truly fatal error.
2. Connectors SHOULD catch exceptions and either handle them gracefully to continue operation
or rethrow them as ConnectException or one of its subtypes.
3. Connectors MUST implement graceful back-off operations that require retires.

**Comment by SAMBASIVA-TATIKONDA** [comment]
Team, Any timeline when this capability will be added?
