### ISSUE TITLE
provide a common pattern for ingestion

### ISSUE THREAD

**Issue by conker84** [neo4j-contrib/neo4j-streams#154]
For ingest, a really common pattern is going to be `MERGE (w:Whatever { id: event.payload.id }) ON CREATE SET w += event.payload;`
This is to basically record the data and just move on.  To do this pattern, all we need is a label, a topic, and an ID.

It would be really cool if you would do all of this for me if I specified in my config something like:

streams.sink.MyCustomerIngester.label=Customer
streams.sink.MyCustomerIngester.id=customerId
streams.sink.MyCustomerIngester.topic=customers

Thanks to @moxious for the suggestion.

**Comment by jexp** [comment]
We should instead use the same pattern we use for the CDC
i.e. 

`...sink.auto.topic=:Label{id,+-prop}`

**Comment by conker84** [comment]
related to #68
