### ISSUE TITLE
provide procedures in order to change configuration at runtime

### ISSUE THREAD

**Issue by conker84** [neo4j-contrib/neo4j-streams#155]
Some procedure like:
`CALL streams.config.setValue(‘streams.source.topic.nodes.neo4j-outbound’, ‘SomeNewValue’)`
Thanks to @moxious

**Comment by moxious** [comment]
Related 
https://github.com/neo4j-contrib/neo4j-streams/issues/181

**Comment by moxious** [comment]
Adding to this, from @davefauth 

There has to be a way to dynamically add / modify / remove configuration settings.

(Customer) wants to use this but doesn't want to have downtime every time you change the topic cypher or add a topic

if it is in the config file, then let us reload the config file

Graphaware did that in some instances.
