### ISSUE TITLE
investigate streams.consume timeout behaviour

### ISSUE THREAD

**Issue by conker84** [neo4j-contrib/neo4j-streams#157]
Starting with an empty topic, I did this: CALL streams.consume('test', { timeout: 2000 }) YIELD event;   the query returned in 800ms

Thanks to @moxious

**Comment by moxious** [comment]
I believe it's probably an exception that's getting swallowed and not reported here:
https://github.com/neo4j-contrib/neo4j-streams/blob/master/consumer/src/main/kotlin/streams/procedures/StreamsSinkProcedures.kt#L39

If there's an exception it should propagage to the caller most likely, unless there are exceptions we know about which can occur which should be handled in some other way.  If this is the case, then still the user should be notified somehow

**Comment by conker84** [comment]
I checked and the behaviour is consistent with the documentation:
https://neo4j-contrib.github.io/neo4j-streams/#_streams_consume
According to the documentation `timeout`: `It’s the value passed to Kafka [Consumer#poll](https://kafka.apache.org/10/javadoc/org/apache/kafka/clients/consumer/KafkaConsumer.html#poll-long-) method (milliseconds). Default 1000`.
With the #178 the behaviour changed in order to wait until the end of the timeout
