### ISSUE TITLE
Extend documented docker-compose file for plugin approach with two neo4j: source and sink

### ISSUE THREAD

**Issue by dmytro-winged** [neo4j-contrib/neo4j-streams#166]
Thank you for your plugin! 
I'm trying to use it in my work. Documentation is good structured. But for plugin approach It has no working `docker-compose` file with two instances of neo4j: one source and one sink. And it has a mistake (at least it seems so to me) in sink yml configuration, you can check [StackOverflow question](https://stackoverflow.com/questions/55446552/how-to-configure-neo4j-sink-instances-with-kafka-and-neo4j-streams).
It would be nice if you can fix and extend documentation to simplify the start of test cluster.

**Comment by mroiter-larus** [comment]
Included this issue into #282
