### ISSUE TITLE
Configuration parameters review

### ISSUE THREAD

**Issue by omarlarus** [neo4j-contrib/neo4j-streams#17]

**Comment by conker84** [comment]
Are all the required parameters present?

Moreover, in order to improve readability we propose to change:
```
kafka.topics=topic1,topic2
kafka.patterns=topic1:*;topic2:Label1 {prop1, prop2}
```
In:
```
kafka.topics=topic1,topic2
kafka.patterns.topic1=*
kafka.patterns.topic2=Label1 {prop1, prop2}
```

**Comment by conker84** [comment]
According to the Kafka source code the [Topic](https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/common/internals/Topic.java) has as admitted chars:
```java
public static final String LEGAL_CHARS = "[a-zA-Z0-9._-]";
```
so we must continue with the existing structure.

**Comment by jexp** [comment]
we can also just take anything behind `kafka.patterns.*`

**Comment by conker84** [comment]
We propose to delete the `kafka.topics` property and use these:

```
kafka.patterns.nodes=topic1:*;topic2:Label1{prop1, prop2}
kafka.patterns.relationships=topic1:*;topic2:REL{prop1, prop2}
```

 This means that we have to refactor the `NodePattern` class in order to parse relationships as well

**Comment by jexp** [comment]
Hmm it probably gets messy quickly.

I think we should stick with your original idea:

```
kafka.patterns.nodes.topic1=*
kafka.patterns.nodes.topic2=Label1{prop1, prop2}
kafka.patterns.relationships.topic1=*
kafka.patterns.relationships.topic2=REL{prop1, prop2}
```
