### ISSUE TITLE
Create a Dead Letter Queue

### ISSUE THREAD

**Issue by conker84** [neo4j-contrib/neo4j-streams#177]
Create a Dead Letter queue for unprocessed messages.

Related to #102 and #97

**Comment by conker84** [comment]
Kafka Connect provides out-of-the-box support for Dead Letter Queues:
https://www.confluent.io/blog/kafka-connect-deep-dive-error-handling-dead-letter-queues
but **it not supports the `put` phase** which is important because of this simple use case:
1. we defined this simple cypher query `MERGE (u:User{ssn: event.ssn}) ON CREATE set u.name = event.name, u.surname = event.surname`
2. if for some reason the event.ssn is `null` => Neo4j throws an Exception

We want to manage these kinds of use-cases by collecting these messages into the `Dead Letter Queue`. 
In the case of the Kafka Connect plugin would be cool having direct access to the configured [DeadLetterQueueReporter](https://github.com/apache/kafka/blob/2e91a310d7/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/errors/DeadLetterQueueReporter.java)

In the case of the Neo4j plugin, we must provide our own implementation that, I think, should behave just like the Kafka Connect plugin

**Comment by sintezcs** [comment]
@conker84 Do you have any estimates when this functionality will be implemented?

**Comment by conker84** [comment]
@sintezcs please check the #204 and let us have your feedback.
Thanks a lot!

**Comment by sintezcs** [comment]
@conker84 Thanks! I've looked through your PR and the logic looks fine for me. I'll be waiting to try out this functionality!

**Comment by conker84** [comment]
@sintezcs the PR is merged!

**Comment by conker84** [comment]
For the Kafka Connect plugin I opened this issue in the Kafka JIRA:

https://issues.apache.org/jira/browse/KAFKA-8597
