### ISSUE TITLE
Documentation Improvements for GTM

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-streams#180]
* [x] change docs layout to chunked
* [x] add visual getting started guide for connect plugin
* [x] add documentation for confluent cloud
* [ ] add example for fraud events
* [x] decide where to put it on neo4j.com

**Comment by moxious** [comment]
Two items on this ticket were closed by https://github.com/neo4j-contrib/neo4j-streams/pull/215

The remainder leaving here.

**Comment by jexp** [comment]
Only example question left.

**Comment by moxious** [comment]
GTM long passed, docs evolved quite a bit since then.  ;)
