### ISSUE TITLE
Manage a Cypher template

### ISSUE THREAD

**Issue by omarlarus** [neo4j-contrib/neo4j-streams#19]
https://meet.google.com/linkredirect?authuser=0&dest=https%3A%2F%2Fmedium.com%2Fneo4j%2F5-tips-tricks-for-fast-batched-updates-of-graph-structures-with-neo4j-and-cypher-73c7f693c8cc

**Comment by conker84** [comment]
We'll define a set of properties into `neo4j.conf`:

`streams.sink.topic.<TOPIC_NAME>=<CYPHER_QUERY>`

the next step is the #46
