### ISSUE TITLE
High CPU usage when kafka even sink is enabled

### ISSUE THREAD

**Issue by sintezcs** [neo4j-contrib/neo4j-streams#195]
I'm observing really high CPU usage when I enable Kafka event sink. There are no messages in Kafka, and no queries are being executed in Neo4J. But CPU usage looks abnormal to me. The CPI load doesn't decrease until I stop the Neo4J instance.  

**Kafka event sink enabled**
<img width="705" alt="Screenshot 2019-06-07 at 17 49 43" src="https://user-images.githubusercontent.com/2989480/59113063-0623b000-894d-11e9-8b31-da9dab353dc4.png">

If I disable the event sink, I see normal CPU usage.

**Kafka event sink disabled**
<img width="704" alt="Screenshot 2019-06-07 at 17 50 49" src="https://user-images.githubusercontent.com/2989480/59113119-22bfe800-894d-11e9-8393-518c8917431c.png">

## Expected Behavior (Mandatory)
CPU usage should not be high when Kafka event sink is not processing anything.

## Actual Behavior (Mandatory)
CPU usage is high above average when Kafka event sink is enabled.

### Steps (Mandatory)

  1. Configure and enable Kafka event sink
  2. Start Neo4J
  3. Monitor the CPU load

### Versions

  - OS: Mac OS 10.14.5
  - Neo4j: 3.4.0
  - Neo4j-Streams: 3.4.0

**Comment by jexp** [comment]
@conker84 should be easily findable with profiling probably those busy-wait places we discussed

**Comment by conker84** [comment]
@sintezcs can you try with the following jar?
[neo4j-streams-3.4.2.jar.zip](https://github.com/neo4j-contrib/neo4j-streams/files/3275246/neo4j-streams-3.4.2.jar.zip)
Thanks a lot!

**Comment by sintezcs** [comment]
@conker84 thanks! I've checked this version and it works fine for me, I do not see the abnormal CPU load anymore.
