### ISSUE TITLE
Question about ManualCommitEventConsumer logic

### ISSUE THREAD

**Issue by sintezcs** [neo4j-contrib/neo4j-streams#196]
@conker84 
I am a little bit confused about the current implementation of `KafkaManualCommitEventConsumer`. I am looking at the [read](https://github.com/neo4j-contrib/neo4j-streams/blob/master/consumer/src/main/kotlin/streams/kafka/KafkaEventSink.kt#L304) method, and it looks like it always commits the offset. It doesn't matter if cypher query succeeded or not, because there is a `try..catch` block around `action` method calls, and commit happens outside of try..catch. I thought that the logic should be like:
```
try {
    action()
    commit()
}
except {
    log errors, do smth
}
```

Can you please explain, what is the point of having such logic that us currently implemented? How it will help us to solve https://github.com/neo4j-contrib/neo4j-streams/issues/102 and how can we achieve "at-least-once" delivery with such logic?

**Comment by conker84** [comment]
Hi @sintezcs our idea is to always commit with the daemon job and then with the #177 re-route all the failing messages to the DLQ, we allow the manual commit behaviour with the `streams.consume` procedure where the user can specify if he wants to commit or not the offset. But we are absolutely open to this so please let's discuss.

**Comment by conker84** [comment]
@sintezcs do you need further details? Or can we close this?

**Comment by conker84** [comment]
I'm closing this, feel free to reopen in case need additional info
