### ISSUE TITLE
Define the Sink (Consumer) form

### ISSUE THREAD

**Issue by omarlarus** [neo4j-contrib/neo4j-streams#21]
Is a neo4j internal component or an external process?

**Comment by omarlarus** [comment]
The solution should be external from database because:
- The bolt driver manages the cluster topology
- Can be stopped and updated independently from the database
- Loose coupling 
- Independent scaling

The drawbacks are:
- Performances (network latency)
- Monitoring

**Comment by albertodelazzari** [comment]
@omarlarus I did something on this, based on the Kafka Connect. I can share the code. My solution is an external component that relies on the Noe4j Java Driver.
