### ISSUE TITLE
Issue with neo4j streams to discover Leader from the given Neo4j cluster

### ISSUE THREAD

**Issue by surajrrao** [neo4j-contrib/neo4j-streams#214]
Hi @jexp 

Below a sample connector job that i have to pull date from Kafka topic & write it to Neo4j. One of issue that i have is - i have to change the Neo4j server URI manually whenever the LEADER changes. Is there an option in the connector to discover the leader automatically

{
  "name": "sink_connector_job_1",
  "config": {
    "tasks.max": "1",
    "topics": "customer",
    "connector.class": "streams.kafka.connect.sink.Neo4jSinkConnector",
    "errors.retry.timeout": "-1",
    "errors.retry.delay.max.ms": "1000",
    "errors.tolerance": "none",
    "errors.log.enable": true,
    "errors.log.include.messages": true,
    "neo4j.server.uri": "bolt://xxxxxxxxx:7687",
    "neo4j.authentication.basic.username": "neo4j",
    "neo4j.authentication.basic.password": "connect",
    "neo4j.encryption.enabled": false,
    "neo4j.topic.cypher.customer": "<< Query goes here >>"
    }
}

**Comment by moxious** [comment]
@surajrrao are you able to specify as the server URI bolt+routing://xxxxxx:7687?   By using a bolt routing driver, it should automatically talk to the right member even as the cluster topology changes.

Docs here: https://neo4j.com/docs/driver-manual/1.7/client-applications/?_ga=2.202436881.1613254459.1563135294-1756057251.1510415792#routing_drivers_bolt_routing
