### ISSUE TITLE
Neo4j only load 1000 event from kafka

### ISSUE THREAD

**Issue by xertxiao** [neo4j-contrib/neo4j-streams#218]
## Expected Behavior (Mandatory)
So I am expecting the neo4j to take in all the data from kafka, and whenthere are new data being sent to kafka, neo4j shall also get them.
I used a generator to send random data to kafka, and in kafak I can see that there are over 10000 events so that means I should get 10000 entities in the neo4j database

## Actual Behavior (Mandatory)
When I start the server, neo4j immediately  take in 1000 events, but then it stops getting data from kafka
![image](https://user-images.githubusercontent.com/31442290/61910201-ce66cc80-aee8-11e9-8398-711d2f92f54c.png)
There are only 1000 entities being created
My guess was that the neo4j only poll once from kafka and then never poll again or wait for a very long period of time so i cannot see the update.
I am wondering if there is a setting somewhere I should set to make neo4j keeps polling

### Simple Dataset (where it's possibile)

```
CREATE (n:Entity) SET n = event

```

### Steps (Mandatory)

  1. write a docker file and configure it
  2. deploy it 
  3.send data to kafka, wait in neo4j server to see 

## Screenshots (where it's possibile)
This is the configurations I wrote into the conf file
![image](https://user-images.githubusercontent.com/31442290/61910367-4f25c880-aee9-11e9-8b3c-abaadb5cdf05.png)

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS:
  - Neo4j:3.5.3
  - Neo4j-Streams:3.5.3

**Comment by conker84** [comment]
Hi @xertxiao do you see anything into the log?

**Comment by xertxiao** [comment]
@conker84 Hi! Thanks for replying, I checked the log and it does not tell me anything useful... it only shows the following:
![image](https://user-images.githubusercontent.com/31442290/61971286-8e105880-af93-11e9-9177-943bda07ee96.png)
And i am not sure how could these warnings be related to the issue, thanks

**Comment by conker84** [comment]
can you try to start the server with debug log?

You can add the following configuration:

`dbms.logs.debug.level=DEBUG`

I'll look forward to your feedback!

**Comment by conker84** [comment]
@xertxiao ping

**Comment by xertxiao** [comment]
@conker84 Oh I am sorry... for right now I decided to use the Java api with Neo4j for the project,  but in the future I might come back and work on Kafka connector, is it possible to close this issue for now and reopen it in the future?

**Comment by xertxiao** [comment]
@conker84 Thank you a lot for helping : ) I apologize for forgetting this issue again...

**Comment by xertxiao** [comment]
@conker84 Hi, sorry for taking so long to get back to you, here are some the the DEBUG info i find, the ones about "sent record in ...." are suspicious. I only want kafka -> neo4j but not the other direction. I thought this is neo4j replying to kafka about its position and offset, but why is it always null? Thanks

![image](https://user-images.githubusercontent.com/31442290/62740769-8fa73b00-b9ed-11e9-9398-d677f542315a.png)
![image](https://user-images.githubusercontent.com/31442290/62740771-92099500-b9ed-11e9-94e5-19aa16c18700.png)

**Comment by xertxiao** [comment]
And though the writing job is finished, neo4j DEBUG logger still keeps sending these "Sent record in partition null ..." messages

**Comment by xertxiao** [comment]
The problem has been solved, the cause of the problem is that by default the both
'streams.source.enabled=true'
and
'streams.sink.enabled=true'

you may want to explicitly disable one of them for your purposes
