### ISSUE TITLE
Kerberos connection

### ISSUE THREAD

**Issue by BaptisteGh** [neo4j-contrib/neo4j-streams#219]
Hi everyone,

I would like to know if it was possible to consume or produce on a kerberos authenticated kafka cluster ?
I didn't read anything about it in the documentation.

If it is not, is it a next feature ?

Thanks!

**Comment by moxious** [comment]
Hi @BaptisteGh yes it should be possible.  Under the covers, neo4j-streams uses the official java libraries for kafka, so you would configure this the same way you'd configure them for the java client.   

I found for example this tutorial dealing with how to connect using the right properties for kerberos:

https://henning.kropponline.de/2016/02/21/secure-kafka-java-producer-with-kerberos/

The only difference should be that where kafka docs say to use configuration `kafka.x.y` you would instead here use configuration `streams.kafka.x.y`. 

We're in the process of updating documentation to make this more clear.

**Comment by BaptisteGh** [comment]
Hi moxious,

This is clear ! Thank you
