### ISSUE TITLE
Message from Kafka topic is not populating Neo4J database

### ISSUE THREAD

**Issue by gopinathankm** [neo4j-contrib/neo4j-streams#220]
Based on this blog All About the Kafka Connect Neo4j Sink Plugin in Confluent web site: https://www.confluent.io/blog/kafka-connect-neo4j-sink-plugin I tried to push data Kafka to neo4j database. So far I could this database, nodes or relationships. I have done as follows:

1. Downloaded neo4j/kafka-connect-neo4j:1.0.2 from Confluent hub, unzip and copied to /share/java folder
2. I made up and running all Kafka ecosystem, Zookeeper, Kafka broker, schema-registry, kafka-connect. All working!
3. Create the sink instance by posting configuration to the /connectors endpoint as suggested. Both connector and task is RUNNING!
#****************************************************************************************
`(base) user@user-Lenovo-G400:~/confluent-5.2.2$ curl localhost:8083/connectors/Neo4jSinkConnector/status | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   170  100   170    0     0  34000      0 --:--:-- --:--:-- --:--:-- 34000
{
  "name": "Neo4jSinkConnector",
  "connector": {
    "state": "RUNNING",
    "worker_id": "127.0.1.1:8083"
  },
  "tasks": [
    {
      "id": 0,
      "state": "RUNNING",
      "worker_id": "127.0.1.1:8083"
    }
  ],
  "type": "sink"
}

(base) user@user-Lenovo-G400:~/confluent-5.2.2$ curl localhost:8083/connectors/Neo4jSinkConnector/tasks/ | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   728  100   728    0     0   236k      0 --:--:-- --:--:-- --:--:--  236k
[
  {
    "id": {
      "connector": "Neo4jSinkConnector",
      "task": 0
    },
    "config": {
      "connector.class": "streams.kafka.connect.sink.Neo4jSinkConnector",
      "errors.retry.timeout": "-1",
      "errors.log.include.messages": "true",
      "neo4j.topic.cypher.my-topic": "MERGE (p:Person{name: event.name, surname: event.surname, from: AVRO}) MERGE (f:Family{name: event.surname}) MERGE (p)-[:BELONGS_TO]->(f)",
      "neo4j.authentication.basic.password": "nimmy321",
      "topics": "my-topic",
      "neo4j.server.uri": "bolt://localhost:7687",
      "errors.retry.delay.max.ms": "1000",
      "task.class": "streams.kafka.connect.sink.Neo4jSinkTask",
      "neo4j.authentication.basic.username": "neo4j",
      "name": "Neo4jSinkConnector",
      "errors.tolerance": "all",
      "neo4j.encryption.enabled": "false",
      "errors.log.enable": "true"
    }
  }
] `
#***************************************************************************************************
4. Started JAR file to run the Kafka event data generator for nodes and relationships. 
4A.target$ java -jar neo4j-streams-sink-tester-1.0.jar -f AVRO -e 100
4B.Properly generated messages in Kafka topic!
#****************************************************************************************
�Name 1928714201Surname C
�Name -701016323Surname B
� Name -1015014119Surname B
�Name 2017599767Surname C
� Name -1201788581Surname E
�Name 949517474Surname E
�Name 2031739159Surname C
�Name 476790294Surname E
^CProcessed a total of 300 messages
#****************************************************************************************
3. But nothing is showing in neo4j database for this nodes and relationships.
I am using Neo4j server community edn. 3.5.8, kafka 2.2.0 from Confluent 5.2.2
I can see Neo4JSinkConnector in RUNNING state in Confluent control center also.
Can any body point out what mistake I doing? Any further details required?
![neo4j1](https://user-images.githubusercontent.com/6606671/62311694-fe463f00-b4a9-11e9-9571-80eaf039ad29.png)
![neo4j0](https://user-images.githubusercontent.com/6606671/62311704-03a38980-b4aa-11e9-9091-4682a356ea19.png)

With Regards
Gopinathan K.M

**Comment by moxious** [comment]
In this part:

```
"neo4j.topic.cypher.my-topic": "MERGE (p:Person{name: event.name, surname: event.surname, from: AVRO}) MERGE (f:Family{name: event.surname}) MERGE (p)-[:BELONGS_TO]->(f)",
```

The from: AVRO part looks wrong, like the query is invalid.   AVRO is not a bound variable in this context, and so should probably be `from: "AVRO"`.

Have you tried executing this query manually with a faked event to make sure it works?  You could do something like this to simulate what the connect worker is doing.

```
WITH [{ some: "data" }] AS events
UNWIND events as event
(your query here)
```

**Comment by moxious** [comment]
Any follow up or further question?

**Comment by gopinathankm** [comment]
Sorry for the delayed response. I do thanks you for the reply. As such you can close the issue.
Many thanks!
