### ISSUE TITLE
Kafka Connect Sink configuration option for providing multiple server uris of neo4j casual cluster

### ISSUE THREAD

**Issue by SAMBASIVA-TATIKONDA** [neo4j-contrib/neo4j-streams#221]
Current kafka connect sink configuration is limited to specify the single serverUri. If the single server uri mentioned for connector configuration is down for maintenance or some other reason, connector is not event getting started even though rest of the nodes are still running in the cluster. If connector configuration is allowed to specify more than one server uri with additional property something like serverUris, that way connector can be started by reaching the one of the available server.

**Comment by conker84** [comment]
Hi @SAMBASIVA-TATIKONDA the Kafka Connect Sink uses the Neo4j Java Driver under the hood so you can specify a `bolt+routing` url

**Comment by SAMBASIVA-TATIKONDA** [comment]
@conker84, We are using bolt_routing url for specifying the serverUri itself. However, that particular single server is down. It can't even reach the mentioned server to get the additional cluster member information. So, bolt+routing is helping much either.

**Comment by SAMBASIVA-TATIKONDA** [comment]
@conker84 , Currently, we are creating the driver object using GraphDatabase driver method.

Neo4jService.kt
this.driver = GraphDatabase.driver(this.config.serverUri, authToken, neo4jConfig)

Solution1:
---------

From Neo4j Java driver GraphDatabase API docs, I found routingDriver method which is also promising. this method might have implemented the requesting logic already.

https://neo4j.com/docs/api/java-driver/current/org/neo4j/driver/v1/GraphDatabase.html#routingDriver-java.lang.Iterable-org.neo4j.driver.v1.AuthToken-org.neo4j.driver.v1.Config-

Can we switch to this method for creating the driver object. That way, we can introduce another config property called serviceUris and take list of bolt+routing uris

Solution2:
---------

For example the code below

    public static Driver acquireDriver(List<String> uris, AuthToken authToken, Config config)
    {
        for (String uri : uris)
        {
            try {
                return GraphDatabase.driver(uri, authToken, config);
            }
            catch (ServiceUnavailableException ex)
            {
                // This URI failed, so loop around again if we have another.
            }
        }
        throw new ServiceUnavailableException("No valid database URI found");
    }



        URIs.add("bolt+routing://hostname1:26000");
        URIs.add("bolt+routing://hostname2:26000");
        URIs.add("bolt+routing://hostname3:26000");

Driver driver = acquireDriver(URIs, AuthTokens.basic("username", "password"), Config.build().withLogging(new JULogging(Level.FINE)).toConfig());

Solution 3:
----------

Neo4j Java Driver 1.7 version we have implemented Custom Address Server Resolver that should help

https://medium.com/neo4j/new-features-in-1-7-neo4j-drivers-4bde893b1374

Could you please share your thoughts on mentioned thoughts. If any make sense, can you incorporate the fix.

Thanks very much for all your help.

**Comment by SAMBASIVA-TATIKONDA** [comment]
@conker84 , Could you please share your thoughts and feedback on this. I am hoping that routingDriver solution will fix the issue. Thanks

**Comment by conker84** [comment]
Let me think what is the best combination of backwards compatibility and new feature support.
I'll be back with a solution.

**Comment by moxious** [comment]
Hi @SAMBASIVA-TATIKONDA, discussed this issue today with some colleagues.  A thing we think should be tried, which aligns with best practices for Neo4j, is to create a single DNS record with multiple A entries.   Many customers of Neo4j create a name like "mycluster.mycompany.com" and it resolves to a single A entry per cluster member IP address.  In this way, you point the client address at that DNS entry, and I think there's a good chance the driver will take care of this for you.

There is a second option we researched, which is cluster bootstrap address resolution, which is done in the driver, docs are here:  https://neo4j.com/docs/driver-manual/current/client-applications/#_cluster_bootstrap_address_resolution

The problem with that approach is that it does require extra code and configuration of the Kafka connect worker and/or Neo4j plugin, and notably, the issue that you're reporting should apply to all bolt+routing clients of your cluster.   It's for this reason that we'd suggest looking into the DNS resolution first, since it is an approach you could use for any client of your database and not just the Kafka connect worker.

Please give this a try and report back how it goes.

**Comment by SAMBASIVA-TATIKONDA** [comment]
@moxious , Thanks for the update.

I have discussed this suggestion with my team internally. We currently use the approach of explicitly listing discovery members for neo4j causal cluster config. Changing the initial lookup of core servers ip addresses for cluster formation to DNS is a foundational change to us (https://neo4j.com/docs/operations-manual/current/clustering/setup-new-cluster/#causal-clustering-discovery-dns). We are in the process of moving away from bare metal deployment of neo4j to Kubernetes based cloud environment deployment anyways. At that point in time, DNS based solution won't help either. So, can't go with DNS solution for these reasons.

Just FYI, Our primary client interfaces of neo4j for loading data is through this neo4j sink connector. Rest of the onetime static loads happens through csv load tool directly on the server. Fix is pretty much needed for the connect sink interface at the moment.

Most of the sink connectors we use today already have this multi server uri config lookup option like DSE & Cloudera HDFS sink connectors.

Additional property can be introduced for the neo4j connector sink config like serverUris in addition to the serverUri. Consumers can pick one or the other depends on their cluster setup. serverUris property config can make use of the routingDriver method to create the driver instance which internally handles incremental lookups against all core server uris provided. serverUri property config can continue the current way of creating the driver instance. That way no backward compatibility issuer either.

Could you please revisit the proposed solution and share your thoughts on my response. Once again, thank you very much for your response.

**Comment by moxious** [comment]
@SAMBASIVA-TATIKONDA -- I see.  I've opened a PR that would let serverUris just be a comma-separated list of URIs.  If you specify more than one, you'll be getting a routingDriver.  I've asked @jexp to review this PR.   It seems simple enough that even a separate configuration parameter is not needed in this case.  For Neo4j, to specify more than one address IMPLIES that it's a routing driver and a cluster.

**Comment by SAMBASIVA-TATIKONDA** [comment]
thanks a lot @moxious. This is the fix exactly we are looking for. I am fine with specifying comma-separated list of URI's for current serverUri property itself. Looking for @jexp feedback.
