### ISSUE TITLE
Route all node/relationships to a topic

### ISSUE THREAD

**Issue by conker84** [neo4j-contrib/neo4j-streams#223]
We need to manage cases like this for both nodes/relationships:
streams.source.topic.relationships.<TOPIC_NAME>={*}

So if I want to track CDC on Neo4j and someone adds a new relationship, that will sent out to Kafka automatically

thanks to @davidfauth

**Comment by jexp** [comment]
I guess that's something that we can add generically both for labels and rel-types
and to be consistent perhaps use: `:*{*}` ?

**Comment by NirBarak-RecoLabs** [comment]
Any updates on this? We have a similar use-case and this would solve having to implement post start-up logic.

**Comment by Kavan72** [comment]
@jexp @conker84 this is a very useful case for CUD also. We are looking for this approach but currently is not supported, it would be great if anyone can do this :smiley:
