### ISSUE TITLE
ConsumerRecordKey must not be null

### ISSUE THREAD

**Issue by moxious** [neo4j-contrib/neo4j-streams#230]
Neo4j community site reported this exception:  https://community.neo4j.com/t/getting-consumerrecord-key-must-not-be-null-error-in-neo4j-kafka-streams-plugin/9387/3

I *think* this has already been addressed in a pending PR https://github.com/neo4j-contrib/neo4j-streams/pull/216

This issue is only for tracking this particular exception.  If that PR closes this issue, then so be it; please remember to notify the original poster.

**Comment by jexp** [comment]
Should be handled already in PR #231

**Comment by jexp** [comment]
Needs a release.
