### ISSUE TITLE
use neo4j-streams,run neo4j server error

### ISSUE THREAD

**Issue by nohunt** [neo4j-contrib/neo4j-streams#235]
> Active database: graph.db
> Directories in use:
>   home:         /opt/neo4j-community-3.5.8
>   config:       /opt/neo4j-community-3.5.8/conf
>   logs:         /opt/neo4j-community-3.5.8/logs
>   plugins:      /opt/neo4j-community-3.5.8/plugins
>   import:       /opt/neo4j-community-3.5.8/import
>   data:         /opt/neo4j-community-3.5.8/data
>   certificates: /opt/neo4j-community-3.5.8/certificates
>   run:          /opt/neo4j-community-3.5.8/run
> Starting Neo4j.
> WARNING: Max 1024 open files allowed, minimum of 40000 recommended. See the Neo4j manual.
> 2019-08-28 09:34:45.911+0000 INFO  ======== Neo4j 3.5.8 ========
> 2019-08-28 09:34:45.939+0000 INFO  Starting...
> 2019-08-28 09:34:47.321+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@363a52f' was successfully initialized, but failed to start. Please see the attached cause exception "org.neo4j.kernel.AvailabilityGuard". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@363a52f' was successfully initialized, but failed to start. Please see the attached cause exception "org.neo4j.kernel.AvailabilityGuard".
> org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@363a52f' was successfully initialized, but failed to start. Please see the attached cause exception "org.neo4j.kernel.AvailabilityGuard".
> 	at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:45)
> 	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:187)
> 	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:124)
> 	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:91)
> 	at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:32)
> Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@363a52f' was successfully initialized, but failed to start. Please see the attached cause exception "org.neo4j.kernel.AvailabilityGuard".
> 	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:473)
> 	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
> 	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:180)
> 	... 3 more
> Caused by: java.lang.RuntimeException: Error starting org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory, /opt/neo4j-community-3.5.8/data/databases
> 	at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:230)
> 	at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:146)
> 	at org.neo4j.server.database.CommunityGraphFactory.newGraphDatabase(CommunityGraphFactory.java:41)
> 	at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:90)
> 	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
> 	... 5 more
> Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.extension.GlobalKernelExtensions@416c58f5' failed to initialize. Please see the attached cause exception "org.neo4j.kernel.AvailabilityGuard".
> 	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:434)
> 	at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:66)
> 	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:102)
> 	at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:225)
> 	... 9 more
> Caused by: org.neo4j.kernel.extension.FailedToBuildKernelExtensionException: Failed to build kernel extension KernelExtension:StreamsExtensionFactory[Streams.Producer] because it is compiled with a reference to a class, method, or field, that is not in the class path: 'org/neo4j/kernel/AvailabilityGuard'. The most common cause of this problem, is that Neo4j has been upgraded without also upgrading allinstalled extensions, such as APOC. Make sure that all of your extensions are build against your specific version of Neo4j.
> 	at org.neo4j.kernel.extension.KernelExtensionFailureStrategies.wrap(KernelExtensionFailureStrategies.java:60)
> 	at org.neo4j.kernel.extension.KernelExtensionFailureStrategies.access$100(KernelExtensionFailureStrategies.java:26)
> 	at org.neo4j.kernel.extension.KernelExtensionFailureStrategies$1.handle(KernelExtensionFailureStrategies.java:76)
> 	at org.neo4j.kernel.extension.AbstractKernelExtensions.init(AbstractKernelExtensions.java:72)
> 	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:413)
> 	... 12 more
> Caused by: java.lang.NoClassDefFoundError: org/neo4j/kernel/AvailabilityGuard
> 	at java.lang.Class.getDeclaredMethods0(Native Method)
> 	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
> 	at java.lang.Class.privateGetPublicMethods(Class.java:2902)
> 	at java.lang.Class.getMethods(Class.java:1615)
> 	at sun.misc.ProxyGenerator.generateClassFile(ProxyGenerator.java:451)
> 	at sun.misc.ProxyGenerator.generateProxyClass(ProxyGenerator.java:339)
> 	at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:639)
> 	at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:557)
> 	at java.lang.reflect.WeakCache$Factory.get(WeakCache.java:230)
> 	at java.lang.reflect.WeakCache.get(WeakCache.java:127)
> 	at java.lang.reflect.Proxy.getProxyClass0(Proxy.java:419)
> 	at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:719)
> 	at org.neo4j.kernel.impl.util.DependenciesProxy.dependencies(DependenciesProxy.java:55)
> 	at org.neo4j.kernel.extension.AbstractKernelExtensions.getKernelExtensionDependencies(AbstractKernelExtensions.java:114)
> 	at org.neo4j.kernel.extension.AbstractKernelExtensions.init(AbstractKernelExtensions.java:61)
> 	... 13 more
> Caused by: java.lang.ClassNotFoundException: org.neo4j.kernel.AvailabilityGuard
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 

Currently used versions

### Versions

  - OS: ubuntu 16.04 64bit
  - Neo4j: 3.5.8
  - Neo4j-Streams:3.4.4

**Comment by conker84** [comment]
You are using the wrong plugin version (the v 3.4.4 it's for Neo4j v 3.4.x) please download [this version](https://github.com/neo4j-contrib/neo4j-streams/releases/download/3.5.3/neo4j-streams-3.5.3.jar).
