### ISSUE TITLE
Requests from Google Form

### ISSUE THREAD

**Issue by conker84** [neo4j-contrib/neo4j-streams#239]
I past here a series of feature requests taken from the Google Form, someone needs to be elaborate a little bit more

- [ ] Priority-based reads => needs to be elaborate
- [ ] Ability to start/stop a stream from cypher (not config file). => (partially) related to #94. We want to create/stop new consumers from Neo4j stored procedures
- [ ] Ability to ‘parse’ a message and error handling control. => needs to be elaborate
- [ ] Ability to monitor how the processing of the stream is going and offset management control. (partially) related to #94. We want to monitor the consumers from a Neo4j stored procedure
- [ ] Bulk insert
- [x] Encryption on data in motion => needs to be elaborate but I think it's not it's just about the Kafka security configuration; please look into @ https://docs.confluent.io/3.0.0/kafka/security.html
- [ ] Set labels to nodes though "event" object => needs to be elaborate
- [ ] Ability to add encoding/decoding type from kafka. => needs to be elaborate
- [x] Username and Password for each topic => this is not Neo4j plugin related the user can set the ACL; please look into @ https://medium.com/@stephane.maarek/introduction-to-apache-kafka-security-c8951d410adf

**Comment by jexp** [comment]
Add the security and other related things that are already handled by Kafka and just need to be configured as pointers to the documentation.
