### ISSUE TITLE
Add a versions.json file and connect it up to GitHub pages

### ISSUE THREAD

**Issue by eastlondoner** [neo4j-contrib/neo4j-streams#251]
This is to make this plugin compatibility with neo4j automation / tooling.

The format should match that used by apoc: https://neo4j-contrib.github.io/neo4j-apoc-procedures/versions.json and should live in the neo4j-streams repo.

The information should end up being accessible on this url:
https://neo4j-contrib.github.io/neo4j-streams/versions.json

@jexp seems to know something about how to achieve that

**Comment by moxious** [comment]
@conker84 could you have a look at this?  In principle the solution for this should already be in the APOC source tree, and maybe it can just be carried over to neo4j-streams?   APOC already does this automatically (I guess as part of the build process).  And it too is based on Travis & Java, so hopefully there's a drop-in approach.

**Comment by eastlondoner** [comment]
@moxious / @conker84 any progress on this?

**Comment by moxious** [comment]
APOC uses this gradle job to build the json file: https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/master/build.gradle

In TeamCity, they have a separate job on master which runs this job and checks in the latest on master

**Comment by moxious** [comment]
Resulting versions file is here: https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/master/versions.json

This tends to rely on the fact that these plugins are branched per neo4j version (3.5, 4.0) so nothing's going on the master branch.    All versions.json files are being pushed to master where they can be discovered by a simple URL

**Comment by mneedham** [comment]
Docker PR - https://github.com/neo4j/docker-neo4j/commit/b192927803239c00aa47742366702e890419ff05

**Comment by moxious** [comment]
automation placed in CI pipeline, and versions.json checked into master
