### ISSUE TITLE
Documentation incorrectly states Kafka Sink Plugin can be hosted in Confluent cloud

### ISSUE THREAD

**Issue by rossgabay** [neo4j-contrib/neo4j-streams#256]
According to https://neo4j.com/labs/kafka/ - "You can install the Kafka Connect Neo4j Sink Plugin into Confluent Cloud" which is not an option supported by Confluent Cloud today.

**Comment by moxious** [comment]
@adam-cowley can we transfer this issue to another repo where the labs docs are?   The point being raised is legitimate; customers must host their own infra to run the connect agent with Confluent Cloud

**Comment by adam-cowley** [comment]
Sure, let me know what you'd like changed or you can [edit the file here](https://github.com/neo4j-documentation/labs-pages/edit/master/modules/kafka/pages/index.adoc)

**Comment by moxious** [comment]
Issue is closeable once the linked PR is merged, which I don't have permissions to do.

**Comment by adam-cowley** [comment]
I've merged, the update should be live within the next hour
