### ISSUE TITLE
[Multidatabase] Sink: Implement “sink.to” syntax / config

### ISSUE THREAD

**Issue by conker84** [neo4j-contrib/neo4j-streams#266]
Whenever we sink, we need to know which database that data is going into.

The default behaviour should be to go to the default database if the user doesn’t do any extra configuration.  

Example:

`streams.sink.topic.cypher.accountdetails=SOMECYPHER`

That goes to the default database.   Special note:  the “default default” database is called Neo4j, but we are **not** saying that this configuration should go to the neo4j database.  It should go to whatever is the system configured default database (which will usually be “neo4j”)

Suggestion -- introduce new config syntax `to.database` to make it look more fluent, and specify a DB.  Example:

`streams.sink.topic.cypher.accountdetails.to.myDatabase=SOMECYPHER`

In this form, we’ve explicitly said that the `accountdetails` topic should run cypher on “myDatabase” and the whole config key reads somewhat fluently.    Important:  This also raises the possibility that I could consume accountdetails on multiple different databases.  For example consider this:

```
streams.sink.topic.cypher.accountdetails.to.myDatabase=AccountDetails{*}
streams.sink.topic.cypher.accountdetails.to.anotherDatabase=MATCH (f:Whatever { id: event.id }) SET f.lastUpdate=datetime()
```

So the format is:

`streams.sink.topic.<strategy>.<topic>.to.<database>=whatever`

The full doc is here:
https://docs.google.com/document/d/1V2wqDE25C5XQtegMG4DaH4kmblxj_UHkVa-Iwp_6P8A

**Comment by conker84** [comment]
In sink you’re putting things in neo4j.  If DB goes down -- when do you check to see if it’s back up again?
polling every (configurable `n` minutes) -- “SHOW DATABASES” against the systemdb and check for online status.  It needs to be this because it will work with both Kafka Connect & Plugin. Log messages when you note that databases stop being available and start being available.
Worst case:  If the database becomes unavailable, it’s dead to us until you restart all of neo4j. This is very bad because it means cluster downtime.

**Comment by conker84** [comment]
Also prevent sink into the systemdb with an error at startup

**Comment by conker84** [comment]
Consider that we may need to separate the consumers for each database. One consumer per DB.
This needs a further analysis @moxious for the Kafka Connect Sink because one worker is one consumer so maybe we would prevent multi-database support per sink-config

**Comment by moxious** [comment]
If for Kafka Connect sink you have one worker per consumer....and option is to just say that a kafka connect worker can only work with one neo4j database, and you can sink to multiple databases by deploying multiple connect workers, is this what you're thinking?  This could keep each one clean and simple at the expense of requiring multiples.

**Comment by conker84** [comment]
> .... and you can sink to multiple databases by deploying multiple connect workers, is this what you're thinking? ...
Yes exactly
