### ISSUE TITLE
Fine-grained security: Test & replicate a failed write scenario, handle error appropriately

### ISSUE THREAD

**Issue by conker84** [neo4j-contrib/neo4j-streams#268]
Be aware that weird permissions errors are possible where you will fail to write from the Kafka Connect worker when the permissions are bad. Do that at the validation level so the plugin will not created.
Give error message via regular channels to the user saying that permissions are insufficient to do the sink that they need.

**Comment by conker84** [comment]
Scenario:  
 * User creates a neo4j user called “kafka-sink”.  Gives it read-only privileges on database “foo”.
 * User tells the connect worker to sink Kafka messages -> foo.
 * Connect worker totally fails, because kafka-sink user can’t write.
 * Result:  Standard error handling techniques we already have in place, with a clear message that the bolt username/password used to configure the worker doesn’t have sufficient privileges to work.
   * Use the DLQ -- this isn’t a fatal error.   Just need a really clear message on what to do / how to fix.

**Comment by moxious** [comment]
Issue is mostly addressed right now on the main branch but this is closeable once release is made.
