### ISSUE TITLE
CDC and Kafka Log Compaction

### ISSUE THREAD

**Issue by Solom00n** [neo4j-contrib/neo4j-streams#305]
Hi everyone !! This issue is somehow similar to this one  #272 but the focus here is on Neo4j Streams Source for CDC in tandem with Kafka Log Compaction rather than on Neo4j Streams Procedures.

When using Change Data Capture with Kafka, one of the most common use cases is managing Kafka partitions as logs. In this scenario, Log Compaction is somehow necessary for CDC: we need a complete dataset but we must also avoid unlimited growth in the size of partitions. From the Kafka documentation:

> **Log compaction** ensures that Kafka will always retain at least the last known value for each message key within the log of data for a single topic partition. It **addresses use cases and scenarios such as restoring state after application crashes or system failure or reloading caches after application restarts during operational maintenance.**

On data retention:

> So far we have described only the simpler approach to data retention where old log data is discarded after a fixed period or when the log reaches some predetermined size. **This works well for temporal event data** such as logging **where each record stands alone. However, an important class of data streams are the log of changes to keyed, mutable data (for example, the changes to a database table).**

The current implementation of Neo4j Streams prevents this use cases since the message key is a combination of the transaction id and the id of the event inside the transaction, as shown in the following code ([KafkaEventRouter.kt](https://github.com/neo4j-contrib/neo4j-streams/blob/3.5/producer/src/main/kotlin/streams/kafka/KafkaEventRouter.kt)- line 86 - **sendEvent**  method):
```
private fun sendEvent(partition: Int, topic: String, event: StreamsTransactionEvent) {
        if (log.isDebugEnabled) {
            log.debug("Trying to send a transaction event with txId ${event.meta.txId} and txEventId ${event.meta.txEventId} to kafka")
        }
        val producerRecord = ProducerRecord(topic, partition, System.currentTimeMillis(), 
                 "${event.meta.txId + event.meta.txEventId}-${event.meta.txEventId}",
                JSONUtils.writeValueAsBytes(event))
        send(producerRecord)
    }
```
As far as I know, this will generate a sequence of unique keys, preventing Log Compaction. Instead, choosing the node or relationship id as the message key (``"${event.payload.id}"``) would enable Log Compaction on the Kafka side. However, I'm pretty sure there are specific reasons for creating the key that way: maybe the message keys are used to know where we are in the Neo4j log, to recover after a failure, but I'm not sure.

Can you explain why the keys are generated in this way? Is it possible to enable Log Compaction in Neo4j Streams right now? If the answer is no, I think this is a must-have feature for Change Data Capture. Thanks !!

## Considered alternatives

While writing this issue, I actually came up with a possible alternative solution (the same also applies to the issue #304): one can simply create a microservice using Kafka Streams to add custom logic and cope with order guarantees and log compaction. However, I am still convinced that these problems should be addressed within Neo4j Streams.

**Comment by conker84** [comment]
@Solom00n thanks for the great analysis, we can do it via a configuration param in order to keep both options

**Comment by moxious** [comment]
@mroiter-larus is this issue close-able?

**Comment by mroiter-larus** [comment]
@moxious this had been put on hold that i know of

**Comment by moxious** [comment]
Left open pending duplicate functionality PR agaist 3.5 branch. Issue is closeable when 3.5 branch is merged with same fix/improvement.
