### ISSUE TITLE
Unify kotlin-reflect version

### ISSUE THREAD

**Issue by conker84** [neo4j-contrib/neo4j-streams#306]
Jackson comes with an old version of `kotlin-reflect` package, unified it with the same version used in streams.

**Comment by moxious** [comment]
@conker84 closeable, yes?

**Comment by conker84** [comment]
yes!

**Comment by rmoff** [comment]
@conker84 which version of the connector is this fix in? Is it available on Confluent Hub?

**Comment by moxious** [comment]
@rmoff apologies; Jeff Bean contacted us a while ago about the same issue; this is on the main branch but not in a release yet.  As it's done, we need to cut a new patch release and push it over to Confluent to be "hub-ified".   Will follow up within a day.

**Comment by moxious** [comment]
@rmoff we have just cut this release, which includes this bugfix.  I'll get in touch with the Confluent folks ASAP to start hub publishing.  https://github.com/neo4j-contrib/neo4j-streams/releases/tag/4.0.2

**Comment by conker84** [comment]
@rmoff I just sent the email to Jeff with the link to the new connector
/cc @moxious
