### ISSUE TITLE
(Carryover to 3.5 needed only) Do not check broker topic auto-create if streams.source.enabled=false

### ISSUE THREAD

**Issue by moxious** [neo4j-contrib/neo4j-streams#318]
a customer spotted a weird behaviour of the source connector. Even with streams.source.enabled=false, it seems like it checks the defined topics (streams.source.topic.nodes.<topic> & streams.source.topic.relationships.<topic>) against topics existing in Kafka, if topic-auto-create is not allowed on the broker. Or if those topics have not been specified, they seem to default to the default database name (‘neo4j’).

That gives an unnecessary warning :

WARN The BROKER config auto.create.topics.enable is false, the following topics need to be created into the Kafka cluster otherwise the messages will be discarded: [neo4j, neo4j]

**Comment by moxious** [comment]
@mroiter-larus is this close-able / completed?

**Comment by mroiter-larus** [comment]
@moxious this had been put on hold

**Comment by mroiter-larus** [comment]
@moxious this issue has been fixed with the PR https://github.com/neo4j-contrib/neo4j-streams/pull/347. So this issue can be closed

**Comment by conker84** [comment]
@moxious the bug has been fixed in branch `4.0` with #347, do we need to fix it `3.5`?

**Comment by moxious** [comment]
Yes @conker84 probably so.

**Comment by mroiter-larus** [comment]
@conker84 @moxious 
i did a test with Neo4j 3.5.22 and Neo4j Streams 3.5.12. The bug has already been fixed in the `3.5`
