### ISSUE TITLE
Add section in documentation for JAAS_Plain configuration

### ISSUE THREAD

**Issue by davidfauth** [neo4j-contrib/neo4j-streams#321]
Recommend adding a section in the documentation on how to configure Kafka / Neo4j for JAAS_Plain.

See attached for sample verbage.

[kafka_jaas_plain.txt](https://github.com/neo4j-contrib/neo4j-streams/files/4771816/kafka_jaas_plain.txt)

**Comment by moxious** [comment]
Closing, because as of ticket review this seems to have been solved / merged, with live docs here: https://neo4j.com/labs/kafka/4.0/kafka-ssl/#_authentication_with_sasl
