### ISSUE TITLE
Issues using neo4j sink connector

### ISSUE THREAD

**Issue by wrdelcb** [neo4j-contrib/neo4j-streams#322]
Hello,

I'm working on trying to use Neo4j sink connector (neo4j-kafka-connect-neo4j-1.0.7) to pull data from Kafka (Confluent Platform 5.5.0) but getting the following error:
java.lang.NoClassDefFoundError: Could not initialize class kotlin.reflect.jvm.internal.impl.builtins.BuiltInsLoader.

I tried with KSQL, Json and Control Center,  getting the same issue.

Json:
curl -i -X PUT -H  “Content-Type:application/json” \
    http://localhost:8083/connectors/Neo4jSinkConnector/config \
    -d ‘{
            “connector.class”: “streams.kafka.connect.sink.Neo4jSinkConnector”,
            “topics”: “topicname”,
            “neo4j.server.uri”: “bolt://localhost:7687”,
            “neo4j.authentication.basic.username”: “neo4j”,
            “neo4j.authentication.basic.password”: “****”,
            “neo4j.topic.cypher.topicname”: “MERGE (pc:newnode { pc.Id: event.pId }) ON CREATE SET pc.name=event.name”
        }’

KSQL

CREATE SINK CONNECTOR Neo4jSinkConnector WITH (
    ‘connector.class’= ‘streams.kafka.connect.sink.Neo4jSinkConnector’,
    ‘topics’= ‘topicname’,
    ‘neo4j.server.uri’= ‘bolt://localhost:7687’,
    ‘neo4j.authentication.basic.username’= ‘neo4j’,
    ‘neo4j.authentication.basic.password’= ‘*****’,
    ‘neo4j.topic.cypher. topicname’= ‘MERGE (pc:newnode { pc.Id: event.pId }) ON CREATE SET pc.name=event.name’
);

  - OS: macOS Catalina version 10.15.5 
  - Neo4j: 4.0.4 community version
  - Neo4j-Streams: neo4j-kafka-connect-neo4j-1.0.7

Can someone help me with this. I would really appreciate it. 

Thank you

**Comment by wrdelcb** [comment]
Sorry, could not get the image from confluent platform.

**Comment by conker84** [comment]
@wrdelcb did you find the solution?

**Comment by wrdelcb** [comment]
Hi conker84,

This issue was fixed with the fix that you provide to @rmoff . https://github.com/neo4j-contrib/neo4j-streams/issues/306
Thank you very much for your help on this. I will close this issue. 

@wrdelcb
