### ISSUE TITLE
Neo4j 4 for Aura - Integration testing

### ISSUE THREAD

**Issue by moxious** [neo4j-contrib/neo4j-streams#325]
This ticket is not a bug - just a task to do some compatibility / integration testing with Neo4j 4 running on Aura, which is coming available soon.

Specific changes that I know about in Aura 4 -- which may impact the connect worker and that need testing:

- The `neo4j` user no longer has the admin role
- `CALL dbms.listConfig()` and some other stored procedures as a result cannot be called from the client side
- If we have any versioning switches, these need careful review because `CALL dbms.components()` returns custom information.

**Comment by mroiter-larus** [comment]
Hi @moxious, i made a very simple test trying to connect to a Neo4j Aura instance using Kafka Connect Neo4j Sink plugin with the following credentials:

```
NEO4J_URI=neo4j+s://a01a8c07.databases.neo4j.io
NEO4J_USER=neo4j
NEO4J_PASSWORD=jK54epthtrrFdWLdTnYdKDRv1igCyIJhpBZfKMyfIko
```

When i tried to create the Sink instance, i got the following error (as expected):

```
{"error_code":400,"message":"Connector configuration is invalid and contains the following 1 error(s):\nInvalid value neo4j+s://a01a8c07.databases.neo4j.io for configuration neo4j.server.uri: Scheme must be one of the following. 'bolt', 'bolt+routing', 'neo4j'\nYou can also find the above list of errors at the endpoint `/connector-plugins/{connectorType}/config/validate`"}
```

So currently we can't use Neo4j Streams with Aura because we didn't support the `neo4j+s` schema yet.

**Comment by moxious** [comment]
@mroiter-larus please try again with bolt+routing://.    The default connection URI for Aura is indeed neo4j:// and this does require a java driver update in order to make possible (if we update the streams driver to the latest java driver it will work) -- but even without the latest client, it should still work with bolt+routing

**Comment by conker84** [comment]
@moxious @moxious we have a validation about supported URI schemes:

https://github.com/neo4j-contrib/neo4j-streams/blob/b87c73f9b7755c742dd67281c99347e78ec6e6bc/kafka-connect-neo4j/src/main/kotlin/streams/kafka/connect/sink/Neo4jSinkConnectorConfig.kt#L217-L224

we need to add the others there.

https://neo4j.com/docs/driver-manual/current/client-applications/#driver-connection-uris#d0e972

**Comment by moxious** [comment]
@conker84 OK, in this case, this validation does need to be expanded.  The current neo4j drivers manual includes a number of different variants, including bolt+s, bolt+ssc, etc.  Be careful -- all of those new options are only valid as of 4.0.2 java driver (not 100% sure on that version, but it's > 4.0.0)

See table 2.2 here: https://neo4j.com/docs/driver-manual/current/client-applications/#driver-connection-uris
