### ISSUE TITLE
bolt+routing not working for the property neo4j.server.uri

### ISSUE THREAD

**Issue by philipsamuel** [neo4j-contrib/neo4j-streams#326]
## Guidelines

Please note that GitHub issues are only meant for bug reports/feature requests. If you have questions on how to use Streams, please ask on [StackOverflow](https://stackoverflow.com/questions/tagged/neo4j-streams) instead of creating an issue here.

## Expected Behavior (Mandatory)
We upgraded tried upgrading from neo4j-kafka-connect-neo4j-1.0.3 to neo4j-kafka-connect-neo4j-1.0.7 . 
bolt+routing should work as it used to be in neo4j-kafka-connect-neo4j-1.0.3
"neo4j.server.uri": "bolt+routing://<host>:7687"

## Actual Behavior (Mandatory)
Getting below error

connect            | [2020-07-15 04:57:28,813] ERROR WorkerSinkTask{id=jdbc_neo4j_sink_connector_local-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask)
connect            | java.lang.IllegalArgumentException: Invalid address format bolt+routing
connect            | 	at org.neo4j.driver.internal.Scheme.validateScheme(Scheme.java:46)
connect            | 	at org.neo4j.driver.GraphDatabase.driver(GraphDatabase.java:139)
connect            | 	at streams.kafka.connect.sink.Neo4jService.<init>(Neo4jService.kt:77)
connect            | 	at streams.kafka.connect.sink.Neo4jSinkTask.start(Neo4jSinkTask.kt:29)
connect            | 	at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:301)
connect            | 	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:189)
connect            | 	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
connect            | 	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
connect            | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
connect            | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
connect            | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
connect            | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
connect            | 	at java.lang.Thread.run(Thread.java:748)

## How to Reproduce the Problem
create a sink connector with "neo4j.server.uri": "bolt+routing://<host>:7687"

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS: MacOS
  - Neo4j: 3.5.6
  - Neo4j-Streams: neo4j-kafka-connect-neo4j-1.0.7

**Comment by mroiter-larus** [comment]
Hi @philipsamuel,

Could you please try to use `"neo4j.server.uri": "neo4j://:7687"`.

Thanks,

Mauro

**Comment by philipsamuel** [comment]
Hi @mroiter-larus  - yes that worked . Does this work similar to bolt+routing?

**Comment by conker84** [comment]
@philipsamuel yes it's a replacement for `bolt+routing`
