### ISSUE TITLE
Error while starting connector (org.apache.kafka.connect.runtime.WorkerConnector:118) java.util.ServiceConfigurationError: kotlin.reflect.jvm.internal.impl.builtins.BuiltInsLoader: Provider kotlin.reflect.jvm.internal.impl.serialization.deserialization.builtins.BuiltInsLoaderImpl not a subtype

### ISSUE THREAD

**Issue by prasanthsravan** [neo4j-contrib/neo4j-streams#332]
## Guidelines

Please note that GitHub issues are only meant for bug reports/feature requests. If you have questions on how to use Streams, please ask on [StackOverflow](https://stackoverflow.com/questions/tagged/neo4j-streams) instead of creating an issue here.

## Expected Behavior (Mandatory)
it should start neo4j kafka-connect sink connector normally

## Actual Behavior (Mandatory)

It is thowing error **Error while starting connector (org.apache.kafka.connect.runtime.WorkerConnector:118)
java.util.ServiceConfigurationError: kotlin.reflect.jvm.internal.impl.builtins.BuiltInsLoader: Provider kotlin.reflect.jvm.internal.impl.serialization.deserialization.builtins.BuiltInsLoaderImpl not a subtype**
## How to Reproduce the Problem

properties  set :

name=Neo4jSinkConnector
topics=my-topic
connector.class=streams.kafka.connect.sink.Neo4jSinkConnector
errors.retry.timeout=-1
errors.retry.delay.max.ms=1000
errors.tolerance=all
errors.log.enable=true
errors.log.include.messages=true
neo4j.server.uri=bolt://localhost:7687
neo4j.authentication.basic.username=neo4j
neo4j.authentication.basic.password=test
neo4j.encryption.enabled=false
neo4j.topic.cypher.my-topic=MERGE (p:Person{name: event.name, surname: event.surname}) MERGE (f:Family{name: event.surname}) MERGE (p)-[:BELONGS_TO]->(f)
~      

### Simple Dataset (where it's possibile)

```
//Insert here a set of Cypher statements that helps us to reproduce the problem

```MERGE (p:Person{name: event.name, surname: event.surname}) MERGE (f:Family{name: event.surname}) MERGE (p)-[:BELONGS_TO]->(f)


### Steps (Mandatory)

  1.Spin up kafka server
  1. edit properties for connect-standalone in <kafka-home>/etc/kafka/connect-standalone.properties
  1. edit kafka-connect neo4j properties in sink-quickstart.properties
Run command - 
./connect-standalone <kafka-home>/etc/kafka/connect-standalone.properties <plugin.path>/etc/sink-quickstart.properties

## Screenshots (where it's possibile)


## Specifications (Mandatory)

Currently used versions

### Versions

  - OS:Centos 7
  - Neo4j:1.2.9
    - Neo4j kafka-connect 1.0.7
    - Confluent kafka 5.5.1

**Comment by conker84** [comment]
hi @prasanthsravan can you check with this file:
https://github.com/neo4j-contrib/neo4j-streams/releases/download/4.0.2/neo4j-kafka-connect-neo4j-1.0.7.zip

**Comment by prasanthsravan** [comment]
@conker84 I used it already but there is a jar for Kotlin reflect in that it seems in META-INF/sevices kotlin.reflect.jvm.internal.impl.serialization.deserialization dependency is not mentioned
thats why I am getting this issue

jar file is kotlin-reflect-1.2.51.jar
can you please check this

**Comment by prasanthsravan** [comment]
Ok got it the link which you sent in that Kotlin jar is of higher version
