### ISSUE TITLE
Specify Neo4j Driver UserAgent for Kafka Connect plugin

### ISSUE THREAD

**Issue by mroiter-larus** [neo4j-contrib/neo4j-streams#334]
Specify UserAgent property when building the Neo4j driver into Kafka Connect plugin as follow:

`neo4j-kafka-connect-sink/<kafka-connect-plugin-version>`

**Comment by moxious** [comment]
give that code is merged is this closeable @mroiter-larus ?

**Comment by mroiter-larus** [comment]
@moxious yes, this is closeable
