### ISSUE TITLE
Local build of Neo4j Streams 3.5.9 fails

### ISSUE THREAD

**Issue by LampicJ15** [neo4j-contrib/neo4j-streams#351]
When I try to build the Neo4j Streams Plugin locally the build fails. 

 I clone the repository and run `mvn clean install` as stated in the instructions. The build then fails at the **Neo4j Streams Consumer** module with the following error:

`Failed to execute goal on project neo4j-streams-consumer: Could not resolve dependencies for project org.neo4j:neo4j-streams-consumer:jar:3.5.9: The following artifacts could not be resolved: com.neo4j:neo4j-causal-clustering:jar:3.5.21, com.neo4j:neo4j-causal-clustering:jar:tests:3.5.21: Failure to find com.neo4j:neo4j-causal-clustering:jar:3.5.21 in https://packages.confluent.io/maven/ was cached in the local repository, resolution will not be reattempted until the update interval of confluent has elapsed or updates are forced`

**Comment by conker84** [comment]
Hi @LampicJ15 we added some neo4j enterprise deps so in order to compile it please add the env variable `TRAVIS` with value `true` and it will skip the enterprise deps.
