### ISSUE TITLE
Make DLQ work per database/topic

### ISSUE THREAD

**Issue by conker84** [neo4j-contrib/neo4j-streams#356]
Now the DLQ works as one topic and all the errors got gathered in there.
We should enable it per database and/or topic in order to give to the users a more fine graded control

**Comment by moxious** [comment]
Discussion March 5:

* Start with simple; add a database field to the message in the DLQ to enable "fan-out" by the user on a single DLQ
* Later we can implement multiple DLQs with some specified default.  Always make default config easy & obvious, and allow more complex config by exception
