### ISSUE TITLE
Server and driver issues

### ISSUE THREAD

**Issue by lincolnchoo** [neo4j-contrib/neo4j-streams#357]
Tried to use the neo4j sink connector but received the following issue.

org.neo4j.driver.v1.exceptions.ClientException: The server does not support any of the protocol versions supported by this driver. Ensure that you are using driver and server versions that are compatible with one another.

Can I check which version of confluent and neo4j is the connector suitable for?

Thank you.

**Comment by conker84** [comment]
@lincolnchoo do you have any feedback about @moxious's suggestion?

**Comment by conker84** [comment]
I'm closing this since a lack of feedback, feel free to reopen in case you have any new information.
