### ISSUE TITLE
Documentation missing <title> tag

### ISSUE THREAD

**Issue by moxious** [neo4j-contrib/neo4j-streams#359]
See here: https://neo4j.com/labs/kafka/4.0/overview/

No title in the HTML docs

```
    <title>
        Untitled
        - Neo4j Graph Database Platform
    </title>
```

May be missing an annotation here: https://github.com/neo4j-contrib/neo4j-streams/edit/4.0/doc/asciidoc/index.adoc

**Comment by moxious** [comment]
May be fixed by https://github.com/neo4j-contrib/neo4j-streams/pull/353

**Comment by mroiter-larus** [comment]
@moxious This seems to be already fixed

**Comment by moxious** [comment]
Thanks
