### ISSUE TITLE
Is it possible to specify a schema for CUD events so that neo4j has properties correctly typed?

### ISSUE THREAD

**Issue by andreagentili** [neo4j-contrib/neo4j-streams#360]
From https://neo4j.com/labs/kafka/4.0/consumer/ it seems that CUD format does not support schemas as CDC does.

```
{
  "op": "merge",
  "properties": {
    "foo": "value",
    "key": 1
  },
  "ids": {"key": 1, "otherKey":  "foo"},
  "labels": ["Foo","Bar"],
  "type": "node",
  "detach": true
}
```

What I'd like to achieve is specifiying property type (e.g. `"birthDate": "2020-01-01"` should be considered a neo4j `date` and not a string). Is this possible using CUD-formatted events?

**Comment by mroiter-larus** [comment]
Hi @andreagentili,

currently there's no way to define a specific data type of a property (e.g. date or geospatial coordinate). At the moment the data type is implicitly defined. I mean: 

- `"key": "100"` is a String
- `"key": 100` is an integer.

Hope this helps,

Mauro

**Comment by andreagentili** [comment]
Thank you for the answer!
