### ISSUE TITLE
Source Plugin for Kafka Connect

### ISSUE THREAD

**Issue by moxious** [neo4j-contrib/neo4j-streams#375]
Explore options for building this - particularly for Aura.

Exposed TransactionEventHandlers not yet available- may have to be polling approach of some sort

**Comment by vishnu2497** [comment]
Hi 

we are looking exactly for this source connector for the neo4j.

may i know when this functionality will release?

**Comment by moxious** [comment]
@vishnu2497 we are actively discussing this as a team, how/when to prioritize it.  It hasn't been built yet.  You could really help us by describing your use case & desire for this feature.  Which systems do you want to produce data out to?  In which format?  And so on.

**Comment by vishnu2497** [comment]
Actually we are looking similar thing like Kafka Connectors to pull the
data from neo4j and store into Kafka topic.

We can have a control while using connector kind of stuff but that is not
achievable in current neo4j streams

We need the following functionality

1)Use connector to pull data from neo4j

2)That connect has to be configurable at any time

3)Able to capture the CDC (CHANGE DATA CAPTURE)

4)Able to use query mode also to get the data based on query..

5)Able to pause/resume the connectors.


In a short point Neo4j sink connector for kafka is available already like
that source connector is there means it will be great.

**Comment by ali-ince** [comment]
This is already available, refer to https://neo4j.com/docs/kafka for more information.
