### ISSUE TITLE
Allow deferring starting sink until procedures are registered

### ISSUE THREAD

**Issue by ivangreene** [neo4j-contrib/neo4j-streams#384]
## Feature description (Mandatory)
If a procedure is used within a sink template query, and messages are queued up for consumption before the Neo instance is started (or during a restart), consumption may begin before procedures are registered. This results in an error in consumption and the sink will shut down and need to be restarted.

This could operate in a similar way to how APOC waits for procedures to be available before running initialization queries: https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/4.1/core/src/main/java/apoc/cypher/CypherInitializer.java#L56

## Considered alternatives
No real alternatives other than hacking around to stop and start the sink during database startup

## How this feature can improve the project?
This will allow using procedures within sink template queries without running into problems during startup

**Comment by conker84** [comment]
@ivangreene we already have this for apoc, do you want a more general approach?

**Comment by ivangreene** [comment]
@conker84 yeah I don't know of any way to wait until the procedures are available to start consuming from Kafka. I am using procedures in the Cypher template configurations, so will fail messages that were already on the topic when the server starts up. Is there a way I could make use of the apoc feature here?

**Comment by conker84** [comment]
Sorry I'm not sure what your issue is, do you need to wait for APOC to be registered or for other procedures?

**Comment by ivangreene** [comment]
@conker84 need to wait on some other procedures, but it works just as well to assume APOC needs to be registered. If you use an APOC procedure in a Cypher template query as a sink consumer, it will fail on any messages consumed during startup because it is not available

**Comment by conker84** [comment]
If you want to wait for apoc please check here:
https://github.com/neo4j-contrib/neo4j-streams/blob/3.5/doc/asciidoc/consumer/configuration.adoc

In particular:

```bash
streams.check.apoc.timeout=<ms to await for APOC being loaded, default -1 skip the wait>
streams.check.apoc.interval=<ms interval awaiting for APOC being loaded, default 1000>
```

**Comment by ivangreene** [comment]
@conker84 great! This should help me out, I had not seen those configuration options. It seems like the other procedures get loaded around the same time as APOC (we are calling them from the APOC initializer) so this should work for the other plugins as well
