### ISSUE TITLE
How to set the kafka topic name Dynamically using Neo4j Streams?

### ISSUE THREAD

**Issue by vishnu2497** [neo4j-contrib/neo4j-streams#388]
Hi Guys,

Right now we can able to set the kafka topic in `neo4j.conf` file.

Everytime when we change the topic name we need to restart the database.

**Example:**(Neo4j conf file)
`streams.source.topic.nodes.nodeatest=NodeA{*}`

so can we achieve this scenario dynamically without restarting the database.

**Comment by conker84** [comment]
Hi @vishnu2497 at this very moment is not possible, but we're working on #358 in order to allow that. Until the PR isn't ready you have to restart the database in order to apply the changes.

**Comment by vishnu2497** [comment]
Thanks u so much for this information @conker84 

is there any approximate time /release we expect this PR to merge in neo4j streams.

**Comment by conker84** [comment]
I think that it will be available for the beginning of the year.
