### ISSUE TITLE
Docs in the repo for 4.0 are not getting sync'd properly to the website

### ISSUE THREAD

**Issue by moxious** [neo4j-contrib/neo4j-streams#396]
Already reported to Adam to see if he can look into the build, but he's out of office until January 4.

specifically -- these docs: https://neo4j.com/labs/kafka/4.0/procedures/ are missing the lifecycle procedures we published a while ago.

**Comment by moxious** [comment]
(Update from Guillame)


Currently, we are building the documentation from the 4.0 branch using the path `doc/docs`.
You can take a look at the Antora playbook: https://github.com/neo4j-documentation/docs-refresh/blob/433c0c9afe4e7692d37ca9a792051cac96081a27/labs-docs.yml#L19-L21

The source is here: https://github.com/neo4j-contrib/neo4j-streams/blob/4.0/doc/docs/modules/ROOT/pages/procedures.adoc and it should be published at https://neo4j.com/labs/kafka/4.0/procedures/

This file is correctly processed by Antora, you can get a preview at: https://docs-neo4j.netlify.app/labs/kafka/4.0/procedures/


Please note that this file: https://github.com/neo4j-contrib/neo4j-streams/tree/4.0/doc/asciidoc/procedures won't get processed by Antora because this file is outside the documentation component.

Is doc/docs automatically generated from doc/asciidoc?
Last update on doc/docs is 3 months ago.


--------


The issue seems to be that we had two separate trees for our docs; one was a left-over from the older branch of code, which published using a non-antora build chain.  We also have a new set of docs that publishes via the antora chain.    It seems that when the PR went in for that feature, the original developer committed the right docs to the wrong spot, creating a situation where we had it but the antora build chain was blind to it (as you've pointed out) so it looks like the fix is to re-commit the docs into the right place and fix the original (conceptual) PR error.

**Comment by ali-ince** [comment]
docs are now living in a separate repository.
