### ISSUE TITLE
Move the internal procedures calls to direct API calls

### ISSUE THREAD

**Issue by conker84** [neo4j-contrib/neo4j-streams#407]
i.e. `dbms.cluster.role()`

This will allow to reduce the amount of queries logged inside `query` log

N.b. we can do it only by reflection otherwise we have to include `enterprise` packages

**Comment by moxious** [comment]
Things to watch out for:

- API incompatibilities between 4.0, 4.1, 4.2
- Eventual PR to 4.0+ only, no need to port to 3.5
- Need verification that race condition actually improves

- Problems to be solved:
-- Query log spam (dbms.role())
-- Race condition on leadership detection & writes
