### ISSUE TITLE
Neo4j Streams Logging improvement and Auto-restart system

### ISSUE THREAD

**Issue by mroiter-larus** [neo4j-contrib/neo4j-streams#413]
When using Neo4j Streams as Sink and Kafka is shutted down (manually or for any other reason), Neo4j Streams doesn't log any error. So it's difficult for users to understand by themselves why Neo4j Streams does not consume anymore. 

The expected behaviour should be that Neo4j Streams logs an error and tries to reconnect to Kafka.

**Comment by ali-ince** [comment]
closing this due to plugin deprecation.
