### ISSUE TITLE
Kafka-clients 2.3.0 bug when using LZ4 compression type

### ISSUE THREAD

**Issue by mroiter-larus** [neo4j-contrib/neo4j-streams#450]
Neo4j Streams fails to consume events from a topic which contains compressed events with LZ4 compression type.

According to [https://issues.apache.org/jira/browse/KAFKA-9203](https://issues.apache.org/jira/browse/KAFKA-9203) the solution is to upgrade the kafka-clients library from 2.3.0 to 2.4.0.

**Comment by conker84** [comment]
Fixed by #456 (branch 3.5) and #457 (branch 4.0)
