### ISSUE TITLE
remove references to ZooKeeper

### ISSUE THREAD

**Issue by alexwoolford** [neo4j-contrib/neo4j-streams#454]
ZooKeeper itself is being removed from Kafka and client access to ZooKeeper hasn't been required to produce/consume since v0.9 (circa 2016). Neo4j Streams currently uses v2.3.0 of the client.

My concern with the references to this property is that customers might assume that ZooKeeper access is a requirement and it's not. Confluent Cloud, for example, doesn't expose ZooKeeper to users so a Confluent Cloud user might see this property in the docs and assume they can't use Neo4j Streams.

**Comment by conker84** [comment]
Fixed by #456 (branch `3.5`) and #457 (branch `4.0`)

**Comment by conker84** [comment]
Wrong issue, reopened this one

**Comment by moxious** [comment]
Closed by latest release
