### ISSUE TITLE
How to use bolt+routing in Kafka Neo4j Connector

### ISSUE THREAD

**Issue by Tin-Nguyen** [neo4j-contrib/neo4j-streams#455]
I'm trying to change the protocol from `bolt` to `bolt+routing` in the Kafka Neo4j Connector configuration. However I'm facing the error
```
"trace":"java.lang.IllegalArgumentException: Invalid address format bolt+routing\n\tat org.neo4j.driver.internal.Scheme.validateScheme(Scheme.java:46)\n\tat org.neo4j.driver.internal.SecuritySettings.createSecurityPlan(SecuritySettings.java:64)\n\tat org.neo4j.driver.GraphDatabase.driver(GraphDatabase.java:138)\n\tat streams.kafka.connect.sink.Neo4jService.<init>(Neo4jService.kt:83)\n\tat streams.kafka.connect.sink.Neo4jSinkTask.start(Neo4jSinkTask.kt:29)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:308)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:199)\n\tat org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:185)\n\tat org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:235)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.-bash-4.3$ ps aux | grep java^C                                             hread.run(Thread.java:748)\n"}
```
After reviewing somethings and I get confused on Neo4j Driver. Currently there are 2 neo4j driver: Neo4j JDBC Driver and Neo4j Java Driver. I only see Neo4j JDBC Driver supports bolt+routing, but the Neo4j Java Driver doesn't. I see Sink Connector is using Neo4j Java Driver, wondering how we can use bolt+routing in Sink Connector. 

TIA

**Comment by conker84** [comment]
Can you please try with `neo4j`?

**Comment by Tin-Nguyen** [comment]
@conker84  can you elaborate about `neo4j`? you mean  using `neo4j+routing`?

**Comment by conker84** [comment]
@Tin-Nguyen no just `neo4j` => is a replacement for `bolt+routing`

**Comment by Tin-Nguyen** [comment]
@conker84  it works after I changed the configuration to 
```
"neo4j.server.uri":"neo4j://server1,neo4j://server2,neo4j://server3"
```

Can you explain more about `neo4j` protocol?

**Comment by Tin-Nguyen** [comment]
@conker84  I have another question, we have a front ELB for those neo4j servers I mentioned in my previous comment. Can I just set `neo4j.server.uri=neo4j://elb-dns`, does it still support `routing` happen to select the right leader in the cluster?

**Comment by conker84** [comment]
`neo4j` will work on either a single instance or a cluster. If used on a cluster, it's the equivalent of the `bolt+routing` protocol from Neo4j 3.5.x and earlier, it will route to a cluster member, not necessarily the system at the IP that you specified. Queries executed over that protocol will route according to the transaction functions you're using in your driver...if using a write transaction, they will go to the leader. If using a read transaction, they will route between followers and/or read replicas.

I never tried with ELB but we internally use transaction functions so I'm quite sure that it will work properly

**Comment by Tin-Nguyen** [comment]
Thanks for the information @conker84

**Comment by Tin-Nguyen** [comment]
hi @conker84 , did you aware of any issue related to the routing protocol? After applying the protocol, my system started getting the error
`exception=java.util.concurrent.TimeoutException: Tasks 5 cancelled after timeout of 60000 ms.` Do you now the root cause?

**Comment by conker84** [comment]
Unfortunatelly no

**Comment by conker84** [comment]
I don't think is related to the protocol

**Comment by Tin-Nguyen** [comment]
Thanks @conker84  I will check more and let you know if I figure out any thing.

**Comment by conker84** [comment]
@Tin-Nguyen are you using Aura?

**Comment by Tin-Nguyen** [comment]
@conker84  no we're deploying the neo4j on our VM
