### ISSUE TITLE
Create procedure in order to register topics in real-time

### ISSUE THREAD

**Issue by conker84** [neo4j-contrib/neo4j-streams#46]
Create a procedure:

`call streams.register(topic, statement, {config})`

That allow to register topics into graph properties in real-time

**Comment by moxious** [comment]
Related to "dynamic configuration" see also https://github.com/neo4j-contrib/neo4j-streams/issues/289

**Comment by moxious** [comment]
Closed by addition of dynamic configuration possibilities in 3.5 & 4.0
