### ISSUE TITLE
Kafka sink ignores neo4j.batch.timeout.msecs when neo4j.batch.parallelize = false

### ISSUE THREAD

**Issue by davidfauth** [neo4j-contrib/neo4j-streams#464]
## Source
Reported from Neo4j Startup user

## Expected Behavior (Mandatory)
Kafka Sink has a neo4j.batch.timeout.msecs to timeout the query and uses it.

## Actual Behavior (Mandatory)
The Kafka Sink has a neo4j.batch.timeout.msecs to timeout the query, but when neo4j.batch.parallelize = false, the SINK doesnt care about the timeout at all. The Sink code doesnt use the timeout.msecs setting at all in parallelize false.

### Versions

  - Neo4j: 4.2.x EE
  - Neo4j-Streams: 4.0.4

**Comment by moxious** [comment]
Validated -- we are working on this and have spotted the problem.

**Comment by moxious** [comment]
Closed by recent release
