### ISSUE TITLE
Problem of streams.publish procedure 

### ISSUE THREAD

**Issue by antonio-urbano** [neo4j-contrib/neo4j-streams#466]
## Expected Behavior (Mandatory)
When I use the streams.publish procedure on the relationship, the "label" field is alway empty

## Actual Behavior (Mandatory)
The "label" field in the payload should contain the type of the relationship

## How to Reproduce the Problem
e.g. let's assume to have these nodes and relationship:
(p:Person{name:"P1"})-[:LOVES{type:"friend"}]->(p2:Person{name:"P2"})

and to make this call of the streams.publish procedure:
MATCH (p:Person)-[r]-(p2)
CALL streams.publish('topic', r)

The result is the following:
{"payload":{"id":"2","properties":{"type":"friend"},"label":{},"start":{"id":"0","properties":{"name":"P1"},"labels":["Person"],"type":"node"},"end":{"id":"1","properties":{"name":"P2"},"labels":["Person"],"type":"node"},"type":"relationship"}}

So if I do not explicit  add the relationship type in the call, I lose the information associated to the relationship label

**Comment by conker84** [comment]
@antonio-urbano we plan to do a release latter today, please take a look to the release section
