### ISSUE TITLE
Relationships are not generated using CUD file format as sink ingestion strategy

### ISSUE THREAD

**Issue by mroiter-larus** [neo4j-contrib/neo4j-streams#470]
## Expected Behavior (Mandatory)

Using Neo4j Streams (with both 4.0.6 and 4.0.7 versions) CUD file format sink strategy, relationships should be created without any properties by submitting an event like:

```
{  "op": "merge",
  "from": {
    "labels": [
      "SourceNode"
    ],
    "ids": {
      "key": 1
    }
  },
  "to": {
    "labels": [
      "TargetNode"
    ],
    "ids": {
      "key": "1"
    }
  },
  "type": "relationship",
  "rel_type": "REL_TYPE"
}
```

since the "properties" field is not mandatory, as stated in the documentation

## Actual Behavior (Mandatory)

Relationship between `SourceNode` and `TargetNode` are not generated, even if in the Neo4j log files we can observe that the plugin is reading from topic:

```
...
DEBUG [s.StreamsSinkConfigurationListener] [neo4j] Reading data from topic my-topic
...
```

## How to Reproduce the Problem

  1. Create 2 example nodes `SourceNode` and `TargetNode`
     
```
CREATE(n:SourceNode{key: 1});
CREATE(n:TargetNode{key: 1});
```

  2. Start a `kafka-console-producer` and send an event like the one above
  3. Verify that the event is in the topic by running a `kafka-console-consumer`
  4. The relationship `REL_TYPE` has not been created

### Versions

  - OS: macOS BigSur 11.2.3
  - Neo4j: 4.1.5
  - Neo4j-Streams: 4.0.6, 4.0.7

**Comment by conker84** [comment]
closed via 3b19274
