### ISSUE TITLE
Move to Runnables and Executors?

### ISSUE THREAD

**Issue by conker84** [neo4j-contrib/neo4j-streams#5]
Hi @jexp ,
makes for you sense use Runnables and Executors for this, just as explained by Max De Marzi in his [blog post](https://maxdemarzi.com/2015/03/25/triggers-in-neo4j/)?

**Comment by conker84** [comment]
I made [this](https://github.com/conker84/neo4j-kafka/blob/async/src/main/kotlin/kafka/KafkaModule.kt), If you think that is a good starting point, I can reimplement it with co-routines. Sorry but I didn't know them until now!

**Comment by jexp** [comment]
I like it but we might want to make it configurable.
Also we need to be careful esp. with data that has been deleted (changed) if you access it outside of the current tx you will either not see it anymore (if the tx has been commited) or not see it yet (if data has just been created).

So the read from the graph will have to happen in the current tx only the publication could be async.

Also after discussing with Omar, I was thinking about changing the published record from being a simple data record to something more like an event, with `{ meta, audit, operation, previous, current }`
at least as an option.

**Comment by conker84** [comment]
Great! Just a question because I want to better understand how the trigger management works. Consider this scenario:
1. Some data is created;
2. The Kafka module broadcast the data to consumers in the _beforeCommit_ method;
3. Another Trigger for some reason, maybe one that provide a graph data model validation, rolled back the data;

Is this a possibile scenario?

I think that the switch to the event is better!

**Comment by conker84** [comment]
ping :)

**Comment by jexp** [comment]
Hey sorry. 
We can create the events in beforeCommit but then create a marker that we return and check it it aftercommit/afterrollback and in case of rollback put a negating/cancellation  event on the stream

**Comment by jexp** [comment]
Regarding events it would be good to see what is used by other db's with kafka or eg debezium. I have a call with the latter on Monday

**Comment by conker84** [comment]
Hi @jexp ,
I checked the co-routines and seems they are an [experimental feature](https://kotlinlang.org/docs/reference/coroutines.html#experimental-status-of-coroutines).
Maybe at this point is better to use the runnables?

**Comment by jexp** [comment]
Co-Routines have been along for a long time and should be quite stable.
So I would try to use those.

**Comment by conker84** [comment]
Perfect!
