### ISSUE TITLE
Neo4j streams consuming same message multiple times

### ISSUE THREAD

**Issue by Anunayth** [neo4j-contrib/neo4j-streams#506]
I am using neo4j streams to consume messages from kafka. Kafka messages are read by a custom procedure via neo4j streams.

In neo4j.conf, the following configs have been added

`streams.sink.topic.cypher.topicName=call customProcedure.perfrom(event) yield value return value`
`streams.sink.enabled=true`

From Kafka, i am sending 1346 messages. But in neo4j stream, I can see its consuming more messages that what is sent by kafka. Neo4j Stream is reading same message from kafka multiple times. The number of messages read multiple times are inconsisent for every run. 

1st run --> Number of messages sent = 1346 --> Number of messages received by neo4j = 3315 --> number of repeated messages = 1969
2nd run --> Number of messages sent = 1346 --> Number of messages received by neo4j = 5029 --> number of repeated messages = 3683

Once the total number of unique messages (1346) are received then the sink is stopped. 

I am using 
neo4j 4.1.3
neo4j streams 4.0.4 / 4.0.5 / 4.0.6
apoc plugin 4.1.0.1

neo4j streams beyond 4.0.7 till 4.1.0 are not receiving the messages at all. 

What should i do to stop consumption of these repeated messages?

**Comment by Anunayth** [comment]
Hello @mroiter-larus, 

I checked the issue by making change in the conf file. I also used apoc creation for testing as used by you. 

`streams.sink.topic.cypher.sampleTopic=call apoc.create.node(['TestNode'], {msgId: event.messageId}) yield node return node`

Upon doing so, I could not replicate the issue and 1346 messages were received perfectly. There was no duplication of messages. 

On further investigation, we however found that if a custom procedure is taking some time to execute then this issue can be replicated. 

I gave the following sink configuration in neo4j conf file 

`streams.sink.topic.cypher.sampleTopic=call customProc.testNodeCreation(event) yield node return node`

the exact java code for testNodeCreation is as follows

```
	@Procedure(mode = Mode.WRITE)
	@Description("")
	public Stream<NodeResult> testNodeCreation(@Name("map") Map<String, Object> mapObj) {
		List<NodeResult> returnValue = new ArrayList<>();
		logger.info("testNodeCreation started");
		String messageId = (String) mapObj.get("messageId");
				
		try {
			logger.info("messageId = " + messageId );
		
	                //Thread th = new Thread();
			//th.sleep(4000);
			
                       String cypher = "call apoc.create.node(['TestNode'], {msgId:\" " + messageId 
					+ "\"}) yield node return node";
			Result result = tx.execute(cypher);
			Iterator<Node> nodes = result.columnAs("node");
			while (nodes.hasNext()) {
				logger.info(messageId  + "-->" + nodes.next());
			}
		} catch (Exception e) {
			logger.error(e.getMessage());
		}
		logger.info("testNodeCreation ended");
		return returnValue.stream();
	}
```

This  custom procedure was written to replicate the apoc creation. The code worrked perfectly fine in this case as well. 
I observed the anomaly in behavior when we added the sleep in the code. I added a sleep of 4 seconds (commented in the code snippet). Upon doing so we could see the duplication of message. 

![neo4jStreams_1](https://user-images.githubusercontent.com/9354066/137706176-8a291988-e487-4c22-8f9e-4448e7317a20.png)
![neo4jStreams_2](https://user-images.githubusercontent.com/9354066/137706181-c8eca593-0e98-4793-b272-d1aa8a2b44bb.png)
![neo4jStreams_3](https://user-images.githubusercontent.com/9354066/137706184-d7e2050e-36c7-418d-88fb-3ab6b740de76.png)




Does neo4jStreams require some kind of immediate response from the procedure as acknowledgment? Will neo4jStreams keep sending same message to custom procedure if acknowledgment is not received within stipulated time frame?  I tried to get answers for the same but could not come across any documentation. 

If acknowledgement is required then what should be the format or how can we change acknowledgment criteria?
What shall we do in this situation for removing the duplicity of messages.

**Comment by mroiter-larus** [comment]
Hi @Anunayth,

sorry for the late reply. Are you using auto-commit? If so, could you please try to disable it and then choose one of the two commit mode (commitSync or commitAsync)? Please refers to documentation [here](https://neo4j.com/labs/kafka/4.0/consumer/#_kafka_streams_async_commit) for configuration details.

Regards,

Mauro

**Comment by mroiter-larus** [comment]
Hi @Anunayth,

any news?

Mauro

**Comment by Anunayth** [comment]
Hi @mroiter-larus,

We are still looking into the solution you provided. We will update you soon regarding the status.

Regards, 
Anunay

**Comment by Anunayth** [comment]
Hello @mroiter-larus, 

Apologies for such late response.

We have tested issue based on the suggestions shared by you. 
We were earlier using commitSync (kafka.enable.auto.commit=false). We now have changed it to true. We still can see repeated messages appearing. As per my understanding, in commitASync retrial for the message should not happen. Still we see the same. 

Also, WRT to commitSync, we understand that if response is not sent within 4s (tested with 4s sleep) of time, then a retrial happens. Is it possible to increase this timeout. Instead of 4s (approx) can we manually make it to lets say 30 sec (> time to process each message).

Regards,
Anunay

**Comment by mroiter-larus** [comment]
Hi @Anunayth,

You're right. `commitAsync` does not provide a retrial mechanism. 
However, i'm a bit confused because the 4s sleep is not a time handled by the plugin. It is a sleep time introduced in your custom procedure. Having that said, `commitSync` retry to commit offset until the operation succeed or it fails throwing an exception. One of the possible failure is the timeout managed by the Kafka parameter `default.api.timeout.ms`, which is 60 seconds by default. So, if the offset can't be committed within 60 seconds, the commit operation fails and the plugin will proceed with the next offset.

Hope this helps to clarify.

Regards,
Mauro

**Comment by Anunayth** [comment]
Hi @mroiter-larus,

In `commitSync` what is the default timeout in which if neo4jStreams doesn't receive any response / exception, then it will retry ??

Regards,
Anunay

**Comment by mroiter-larus** [comment]
The time interval between attempting to commit an offset and another is automatically managed by Kafka. What we can customize is just the timeout (`default.api.timeout.ms`), after which Kafka will go for the next offset.

There is another parameter that could cause a bit of confusion: it is the `retry.backoff.ms`. It defines the amount of time to wait before attempting to retry a failed poll request (not an offset's commit) to a given topic partition.

Mauro

**Comment by conker84** [comment]
I'm closing this for lack of feedback, feel free to reopen it in the future
