### ISSUE TITLE
Cud format is in beta ?

### ISSUE THREAD

**Issue by Gwojda** [neo4j-contrib/neo4j-streams#543]
Hi,
I'm using CUD format for data ingest but :
- Merge on relationship use CUDNodeRel instead of CUDNode, so we can not create/merge node while merging relationship. (it is not indicated in documentation, and i think it a big miss)
- Merge on node not using ON CREATE/ON MERGE syntax, so what if we need timestamp at creation ? 
If you can give me tips i can have to look to propose a PR.
Thanks,
Gautier

**Comment by mroiter-larus** [comment]
Hi @Gwojda,

i've recently implemented the feature explained in the issue [542](https://github.com/neo4j-contrib/neo4j-streams/issues/542). Your case seems to be similar. If so, the mentioned feature could solve (at least partially) your problems. I'll let you know as soon as the feature will be released.

Regards,

Mauro

**Comment by Gwojda** [comment]
Ah, great news !!
About the ON CREATE/ON MERGE syntax, do you have any advice to quick fix this ? 
```
--- a/common/src/main/kotlin/streams/service/sink/strategy/CUDIngestionStrategy.kt
+++ b/common/src/main/kotlin/streams/service/sink/strategy/CUDIngestionStrategy.kt
@@ -21,6 +21,7 @@ abstract class CUD {

 data class CUDNode(override val op: CUDOperations,
                    override val properties: Map<String, Any?> = emptyMap(),
+                   val createProperties: Map<String, Any?> = emptyMap(),
                    val ids: Map<String, Any?> = emptyMap(),
                    val detach: Boolean = true,
                    val labels: List<String> = emptyList()): CUD() {
@@ -29,7 +30,7 @@ data class CUDNode(override val op: CUDOperations,
     fun toMap(): Map<String, Any> {
         return when (op) {
             CUDOperations.delete -> mapOf("ids" to ids)
-            else -> mapOf("ids" to ids, "properties" to properties)
+            else -> mapOf("ids" to ids, "properties" to properties, "createProperties" to createProperties)
         }
     }
 }
@@ -105,6 +106,7 @@ class CUDIngestionStrategy: IngestionStrategy {
     private fun buildNodeMergeStatement(labels: List<String>, ids: Set<String>): String = """
             |${StreamsUtils.UNWIND}
             |${buildNodeLookupByIds(keyword = "MERGE", ids = ids, labels = labels)}
+            |ON CREATE SET n += coalesce(event.createProperties,{})
             |SET n += event.properties
         """.trimMargin()

```

Trying this, but not working (crashing with this error: ```
[2022-11-09 15:02:29,120] ERROR [Neo4jSinkConnector|task-0] Error processing 1 messages (streams.kafka.connect.sink.Neo4jSinkTask:30)
org.neo4j.driver.exceptions.ClientException: Expected Property(ReferenceFromSlot(0,event),PropertyKeyName(createProperties)) to be a map, but it was :`NO_VALUE`
        at org.neo4j.driver.internal.util.Futures.blockingGet(Futures.java:111)
        at org.neo4j.driver.internal.InternalTransaction.run(InternalTransaction.java:58)
        at org.neo4j.driver.internal.AbstractQueryRunner.run(AbstractQueryRunner.java:34)
        ``` )
       
Have you any advice ?
Thanks!
Gautier
