### ISSUE TITLE
Structuring nested object causes org.apache.kafka.connect.errors.DataException

### ISSUE THREAD

**Issue by ogawa-takeshi** [neo4j-contrib/neo4j-streams#555]
## Expected Behavior (Mandatory)

Can be structured without exception.

## Actual Behavior (Mandatory)

```
org.apache.kafka.connect.errors.ConnectException: org.apache.kafka.connect.errors.DataException: Invalid Java object for schema type MAP: class org.apache.kafka.connect.data.Struct ...
```

## How to Reproduce the Problem

Specify a `neo4j.source.query` similar to the following:

```
MATCH (n: Test)
RETURN
     ... (skip) ...
    {
        key1: {
            subKey1: "value",
            subKey2: "value"
        },
        key2: {
            subKey1: "value",
            subKey2: true
        }
    } AS nested
```

## Specifications (Mandatory)

Currently used versions

### Versions

  - Neo4j Streams: 5.0.2

**Comment by Emrehzl94** [comment]
This issue is not reproducible in the latest version of the connector. Closing this now, thanks!
