### ISSUE TITLE
Error while starting Kafka-neo4j connect using distributed properties | Error [ java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics]

### ISSUE THREAD

**Issue by ankit302** [neo4j-contrib/neo4j-streams#557]
While starting Kafka-connect with neo4j connector plugins, distributed connector is failed with error;

```
 ERROR Stopping due to error (org.apache.kafka.connect.cli.ConnectDistributed:86)
java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics
        at streams.kafka.connect.utils.PropertiesUtil.<clinit>(PropertiesUtil.kt:15)
        at streams.kafka.connect.source.Neo4jSourceConnector.version(Neo4jSourceConnector.kt:32)
        at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.versionFor(DelegatingClassLoader.java:387)
        at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.versionFor(DelegatingClassLoader.java:392)
        at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.getPluginDesc(DelegatingClassLoader.java:362)
        at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.scanPluginPath(DelegatingClassLoader.java:334)
        at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.scanUrlsAndAddPlugins(DelegatingClassLoader.java:268)
        at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.registerPlugin(DelegatingClassLoader.java:260)
        at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.initPluginLoader(DelegatingClassLoader.java:229)
        at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.initLoaders(DelegatingClassLoader.java:206)
        at org.apache.kafka.connect.runtime.isolation.Plugins.<init>(Plugins.java:61)
        at org.apache.kafka.connect.cli.ConnectDistributed.startConnect(ConnectDistributed.java:93)
        at org.apache.kafka.connect.cli.ConnectDistributed.main(ConnectDistributed.java:80)
Caused by: java.lang.ClassNotFoundException: kotlin.jvm.internal.Intrinsics
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:104)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
```
 
**Configuration of Kafka Server & versions**

Apache Kafka  :- 2.8.2
Neo4j connector plugins 
        "neo4j": "4.4.16",
        "neo4jVersion": "4.4.16",
        "version": "4.1.2"
"homepageUrl": "http://github.com/neo4j-contrib/neo4j-streams/releases/4.1.2"        

 Kafka connect is working fine & up without neo4j plugins jar.
 
 Any support or lead to fix this issue is highly appreciated.

**Comment by mroiter-larus** [comment]
Hi @ankit302 ,

which plugin did you try to install? [neo4j-kafka-connect-neo4j-2.0.2.zip](https://github.com/neo4j-contrib/neo4j-streams/releases/download/4.1.2/neo4j-kafka-connect-neo4j-2.0.2.zip) or [neo4j-streams-4.1.2.jar](https://github.com/neo4j-contrib/neo4j-streams/releases/download/4.1.2/neo4j-streams-4.1.2.jar)?
If you've tried with the Neo4j Streams JAR then you've simply choose the wrong plugin. 

Since you would like to use Neo4j Streams as Kafka Connect connector, you have to install the `neo4j-kafka-connect-neo4j-2.0.2` package. What you need to do is to unpackage it in one of the folder declared into the Kafka Connect `plugin.path` parameter and restart your Kafka Connect. 

Please note that if you're running Kafka Connect in distributed mode, the connector has to be placed in all the Kafka Connect instances.

If you've already done the above steps, could you please share your:

* Kafka Connect configuration 
* Neo4j connector configuration

Hope this helps!

Mauro

**Comment by ankit302** [comment]
Hello @mroiter-larus 
Thankyou !! for your quick response.

Yes i have been using this plugin  [neo4j-kafka-connect-neo4j-2.0.2.zip](https://github.com/neo4j-contrib/neo4j-streams/releases/download/4.1.2/neo4j-kafka-connect-neo4j-2.0.2.zip). Also the connect plugins are copied into respective brokers which are part of cluster & plugin.path is defined where kafka connect jar are kept.


**Cluster configuration**

1. Cluster with 3 kafka broker node & 1 zookeeper node, running on Azure cloud VM instance of ubuntu 20..04 , 

2.  Java version
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu220.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu220.04, mixed mode)

3. Kafka Version
kafka_2.12-2.8.2

 cat /home/azureuser/kafka_2.12-2.8.2/config/connect-distributed.properties
```

# A list of host/pofkart pairs to use for establishing the initial connection to the Kafka cluster.
bootstrap.servers=kafka-0:9092;kafka-1:9092,kafka-2:9092

# unique name for the cluster, used in forming the Connect cluster group. Note that this must not conflict with consumer group IDs
group.id=connect-cluster
key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
# Converter-specific settings can be passed in by prefixing the Converter's setting with the converter we want to apply
key.converter.schemas.enable=false
value.converter.schemas.enable=false

# Topic to use for storing offsets. This topic should have many partitions and be replicated and compacted.

# to run this example on a single-broker cluster and so here we instead set the replication factor to 1.
offset.storage.topic=connect-offsets
offset.storage.replication.factor=2
#offset.storage.partitions=25

# Topic to use for storing connector and task configurations; note that this should be a single partition, highly replicated,

# to run this example on a single-broker cluster and so here we instead set the replication factor to 1.
config.storage.topic=connect-configs
config.storage.replication.factor=2


status.storage.topic=connect-status
status.storage.replication.factor=2
#status.storage.partitions=5

# Flush much faster than normal, which is useful for testing/debugging
offset.flush.interval.ms=10000

# These are provided to inform the user about the presence of the REST host and port configs
# Hostname & Port for the REST API to listen on. If this is set, it will bind to the interface used to listen to requests.
#rest.host.name=
#rest.port=8083

# The Hostname & Port that will be given out to other workers to connect to i.e. URLs that are routable from other servers.
#rest.advertised.host.name=
#rest.advertised.port=

# Set to a list of filesystem paths separated by commas (,) to enable class loading isolation for plugins
plugin.path=/home/azureuser/kafka_2.12-2.8.2/libs,/home/azureuser/kafka_2.12-2.8.2/libs/neo4j-kafka-sink-libs
```


One point to mention here kafka connect work fine when i remove the neo4j jar file from libs 'kafka-connect-neo4j-2.0.2.jar'.
So, It appears to be issue with kafka neo4j connect plugins available.tried with multiple version of Neo4j connector kafka connector 4.X  to 5.X, but still issue persist.Issue is with neo4j kafka connect plugins are written in Kotlin language &  Kafka is in Java & Scala, which leads to dependencies class file not found error, which is not even getting resolved by placing required runtime jars for kotlin at the plugin.path directory where rest of jar are located for kafka connect.


Any help or inputs is highly appreciated.

**Comment by conker84** [comment]
@ankit302 do you still have the issue? Feel free to reopen it in case so. Btw we have successfully installed it into azure with [neo4j-kafka-connect-neo4j-5.0.2-kc-oss.zip](https://github.com/neo4j-contrib/neo4j-streams/releases/download/5.0.2/neo4j-kafka-connect-neo4j-5.0.2-kc-oss.zip)
