### ISSUE TITLE
In Producer where is "Connector" class

### ISSUE THREAD

**Issue by AffanHasan** [neo4j-contrib/neo4j-streams#56]
Compiled this project using maven
In order to use "Producer" to publish "neo4j" database changes to a kafka topic which class should I use as "Connector", consider following config properties:

name=neo4jMessageProducer
topic=neo4j
tasks.max=1
connector.class= "connector class is required here"

 **connector.class** property needs a connector class and I didnt found such class in this project.

**Comment by conker84** [comment]
Hi @AffanHasan thanks for reaching us!
This is not a [Kafka Connector Plug-In](https://docs.confluent.io/current/connect/managing/index.html); it's a [Neo4j plug-in](https://neo4j-contrib.github.io/neo4j-streams/#_installation) that publishes data directly to Kafka topics.
Here you'll find the available [configuration](https://neo4j-contrib.github.io/neo4j-streams/#_configuration)
