### ISSUE TITLE
( Impact on BC/DR - Data loss ) - High priority, Nodes with PointValue property cannot be successfully sink to Neo4j With Neo4j Streams Plugin

### ISSUE THREAD

**Issue by yhhongyang** [neo4j-contrib/neo4j-streams#567]
## Guidelines

Since the original issue (#559) was closed, and the answerer did not understand the issue correctly, so I create a new issue to track.

Please refer to #559 for details.

### Versions

  - Neo4j: 4.3.3
  - Neo4j-Streams: 4.1

**Comment by yhhongyang** [comment]
@conker84 I see you have created a pr to fix the issue based on neo4j stream 5.0, and I am wondering whether this fix will also be implemented on neo4j-streams version 4 which has the `neo4j-streams-plugin`, this plugin is very useful to capture every transactions and send to Kafka

**Comment by conker84** [comment]
I did two PR, one for Streams and one for kafka connect :)
