### ISSUE TITLE
Issue with `$value` parameter in Neo4j Sink Connector with Confluent Cloud Kafka

### ISSUE THREAD

**Issue by tgod009** [neo4j-contrib/neo4j-streams#568]
I'm experiencing an issue with the Neo4j Sink Connector when used with the latest version of Confluent Cloud Kafka. It seems like the connector is not correctly understanding or processing the `$value` parameter.

Here are the details of my setup:

- Neo4j version: 5.9
- Neo4j Streams (Kafka Connector) version: [latest version]
- Kafka version (Confluent Cloud): [latest version]

I've tried just about every possible way of writing this query but still seems to fail 

`WITH $value.user AS user CREATE (u:User {name: user.name})`

Any guidance or assistance with this issue would be greatly appreciated. Thank you.

**Comment by TomVanWemmel** [comment]
It should be `event` without a parameter reference ($). 
The connector polls a bunch of Kafka messages (default 500), splits this into batches (configured with neo4j.batch.size) and creates a transaction per batch. 

As it states in the [documentation](https://neo4j.com/docs/kafka/kafka-connect/sink/#kafka-connect-cypher-strategy):

> Under the hood the Sink inject the event object in this way
> 
> UNWIND $batch AS event
> MERGE (p:Person{name: event.name, surname: event.surname})
> MERGE (f:Family{name: event.surname})
> MERGE (p)-[:BELONGS_TO]->(f)

So don't use any parameter value, but you can use the local variable `event` directly

**Comment by ali-ince** [comment]
@tgod009 did you get it working by following @TomVanWemmel's suggestion?

**Comment by Emrehzl94** [comment]
closing this due to lack of response.
