### ISSUE TITLE
Produce events "from scratch"

### ISSUE THREAD

**Issue by conker84** [neo4j-contrib/neo4j-streams#58]
The Streams Producer should have a procedure `streams.fromScratch` that enables the huge loading of all nodes and relationships into the Kafka topics before tracing each new transactions

**Comment by moxious** [comment]
Use case -- you want to use source, and you want to bootstrap your topic with a full copy of neo4j before enabling source to product subsequent transactions to kafka

**Comment by moxious** [comment]
* How would data be published?  Possibly new eventType
* How to avoid 10 minute transaction timeouts?   Not sure yet.

3rd possibility -- apoc.periodic.iterate with streams.publish -- allows the user to customize their own publish format, while evading transaction timeouts.  Maybe?

**Comment by moxious** [comment]
Starting point -- write apoc.periodic.iterate documentation on how we can address this use case with an example of that.

Include how to use the notion of "filters" for source production, and how you might only want to match parts of the database.  Might want to address the CDC message format.  What should it be, if we don't know what the actual transaction "packets" were after the fact?
