### ISSUE TITLE
log.debug cypher statistics 

### ISSUE THREAD

**Issue by sarmbruster** [neo4j-contrib/neo4j-streams#61]
trace stats (nodes /rels/props) created via log.debug in https://github.com/neo4j-contrib/neo4j-streams/blob/76a20b2afca3d691bf4b2800503004651e51f196/consumer/src/main/kotlin/streams/kafka/KafkaEventSink.kt#L86

**Comment by conker84** [comment]
I'm closing this since we have it in `StreamsEventSinkQueryExecution `:

https://github.com/neo4j-contrib/neo4j-streams/blob/9420823829bbe03e4b1f138b00ddba87af2ee5d0/consumer/src/main/kotlin/streams/StreamsEventSinkQueryExecution.kt#L30-L35
