### ISSUE TITLE
Write our own logical transaction log

### ISSUE THREAD

**Issue by conker84** [neo4j-contrib/neo4j-streams#62]
The transaction handler should be modular, so you can configure more operations when a transaction event is performed. One of these is the file module that:
* write information to rotated logfile
* single line json or avro+thrift (whatever kafka uses) for each change-event
* transactions_from-ts-to-ts-from-txid-to-txid.json / or binary ->
* expose those logical-tx-logfiles via HTTP API (Atom-Feed or REST) and procedures as event-streams

https://github.com/neo4j/neo4j/blob/3.5/tools/src/main/java/org/neo4j/tools/dump/DumpLogicalLog.java
Check if those are actually just physical (record changes) or logical entries (like the tx-event handler)

**Comment by moxious** [comment]
Don't think this is a good idea since Kafka acts as an externalized TX log, and because Neo4j has its own follow-along TX log.  Closing for age; we can re-open if we find a use case.
