### ISSUE TITLE
Pool must happen only in the leader

### ISSUE THREAD

**Issue by conker84** [neo4j-contrib/neo4j-streams#63]
In order to be used in a cluster environment the `consumer.pool` must happen only in the leader.

It must manage also leader change

**Comment by jexp** [comment]
We have code in APOC that does that. 
https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/3.4/src/main/java/apoc/util/Util.java#L592-L607

**Comment by conker84** [comment]
We already [have this](https://github.com/neo4j-contrib/neo4j-streams/blob/master/consumer/src/main/kotlin/streams/utils/Neo4jUtils.kt) and we use it in [StreamsTopicService](https://github.com/neo4j-contrib/neo4j-streams/blob/master/consumer/src/main/kotlin/streams/StreamsTopicService.kt#L22).
Maybe we should do L51 and 52 [here](https://github.com/neo4j-contrib/neo4j-streams/blob/master/consumer/src/main/kotlin/streams/kafka/KafkaEventSink.kt#L51) only if is the leader (so if it is a writeable instance) and then provide a mechanism that subscribe the topics if and only if a new leader is elected (maybe a listner?)

**Comment by jexp** [comment]
Probably for the time being we can just try to write and ignore the exception.
-> even if it's more expensive

And not consume/commit messages until the write went through.

**Comment by jexp** [comment]
Or just check "isWriteable" before the write operation.
