### ISSUE TITLE
Add "Best Practice" Chapter into Documentation

### ISSUE THREAD

**Issue by conker84** [neo4j-contrib/neo4j-streams#83]
## Feature description (Mandatory)
Add Best Practice Chapter into Documentation in order to share with the community how to get the best from the project.

## How this feature can improve the project?
This would help to spread the knowledge about how to use it in real-world scenarios

**Comment by sarmbruster** [comment]
I've just learned that a `poll` in a kafka consumer delivers by default max 500 messages. There's a config option `max.poll.records` to tweak that. Using the consumer from neo4j-streams and depending on the cypher statements used for the topics it makes sense to tweak this to e.g. 5000.
hint: to check how many messages are process per poll, use `call dbms.listQueries() yield queryId, query, startTime,parameters return queryId, query, startTime, size(parameters.events);`

**Comment by moxious** [comment]
Ticket got duplicated into another topic, but is closed now in light of the availability of this documentation right here: https://neo4j.com/labs/kafka/4.0/architecture/
