### ISSUE TITLE
Provide Kafka Connect Sink

### ISSUE THREAD

**Issue by conker84** [neo4j-contrib/neo4j-streams#92]
## Feature description (Mandatory)
Add a Kafka Connect Sink Plugin, that can be used inside the Confluent Platform

## How this feature can improve the project?
This let Kafka users to simply integrate Neo4j into their streaming flow

**Comment by jexp** [comment]
Do you have thoughts on how to integrate with the Schema Registry? I.e. what would make sense?

Perhaps just store our generic schema up to "properties" and just a Map<String,Any> for the data below? or just "Any/Blob" ?

**Comment by jexp** [comment]
Do you have thoughts on how to integrate with the Schema Registry? I.e. what would make sense?

Perhaps just store our generic schema up to "properties" and just a Map<String,Any> for the data below? or just "Any/Blob" ?

**Comment by jexp** [comment]
Actually that's more for the source than the sink. 
For the sink we have no real requirements. As we just pass the data to the cypher statement as it comes in.
