### ISSUE TITLE
Create procedure streams.consume

### ISSUE THREAD

**Issue by conker84** [neo4j-contrib/neo4j-streams#94]
## Feature description (Mandatory)
Create a procedure `streams.consume(<topic>, <cypher>, <config_map>)` that reads data from the topic and executes the provided cypher query with the data that comes from the topic, the config map must provide a `timeout` property that sets the window of listening (zero, means forever)
Also provide two other procedures:
- `streams.consume.list()`: provides a list of all the mappings
- `streams.consume.kill(<topic>)`: kills the consumer

## How this feature can improve the project?
This allows the end user to provide real-time changes to the consumer by adding/removing topics, and provide ad-hoc configurations that could be used just one-time

**Comment by moxious** [comment]
@jexp closeable?  I think this is supported.
